project:
  type: website
  output-dir: docs
  
website:
  title: "Basic stats explained (in R)"
  google-analytics: "G-ZTL54L3SJR"
  navbar:
    left:
      - href: CI.qmd
        text: "Confidence intervals"
      - href: z_t_tests.qmd
        text: "Z and T tests"
      - href: F_test.qmd
        text: "F-test: Test for difference in spread"
      - href: ChiSquare_test.qmd
        text: "ChiSquare"
      - href: regression.qmd
        text: "Ordinary least squares Regression"
      - href: ANOVA.qmd
        text: "Analysis of variance (ANOVA)"
      - href: Logistic.qmd
        text: "Logistic regression"
  page-footer: 
    right: "Creative Commons License, Manny Gimond, 2022" 
  search: 
    location: navbar
    type: overlay
    



format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    minimal: true
    number-sections: true
    code-copy: hover
    anchor-sections: true

execute:
  cache: false
  warning: false
  error: false