<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Basic stats explained (in R) - ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ZTL54L3SJR"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-ZTL54L3SJR', { 'anonymize_ip': true});
</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Basic stats explained (in R)</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./CI.html">
 <span class="menu-text">Confidence intervals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./z_t_tests.html">
 <span class="menu-text">Z and T tests</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./F_test.html">
 <span class="menu-text">F-test: Test for difference in spread</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ChiSquare_test.html">
 <span class="menu-text">ChiSquare</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./regression.html">
 <span class="menu-text">Ordinary least squares Regression</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./ANOVA.html" aria-current="page">
 <span class="menu-text">Analysis of variance (ANOVA)</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Logistic.html">
 <span class="menu-text">Logistic regression</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1</span>  Introduction</a></li>
  <li><a href="#how-a-one-way-anova-is-calculated" id="toc-how-a-one-way-anova-is-calculated" class="nav-link" data-scroll-target="#how-a-one-way-anova-is-calculated"><span class="toc-section-number">2</span>  How a one-way ANOVA is calculated</a>
  <ul class="collapse">
  <li><a href="#the-variance-ratio-method" id="toc-the-variance-ratio-method" class="nav-link" data-scroll-target="#the-variance-ratio-method"><span class="toc-section-number">2.1</span>  The variance-ratio method</a></li>
  <li><a href="#an-example-in-r" id="toc-an-example-in-r" class="nav-link" data-scroll-target="#an-example-in-r"><span class="toc-section-number">2.2</span>  An example in R</a>
  <ul class="collapse">
  <li><a href="#computing-anova-the-hard-way" id="toc-computing-anova-the-hard-way" class="nav-link" data-scroll-target="#computing-anova-the-hard-way"><span class="toc-section-number">2.2.1</span>  Computing ANOVA the hard way</a></li>
  <li><a href="#computing-anova-the-easy-way" id="toc-computing-anova-the-easy-way" class="nav-link" data-scroll-target="#computing-anova-the-easy-way"><span class="toc-section-number">2.2.2</span>  Computing ANOVA the easy way</a></li>
  <li><a href="#anova-as-a-regression" id="toc-anova-as-a-regression" class="nav-link" data-scroll-target="#anova-as-a-regression"><span class="toc-section-number">2.2.3</span>  ANOVA as a regression</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#assumptions-of-anova" id="toc-assumptions-of-anova" class="nav-link" data-scroll-target="#assumptions-of-anova"><span class="toc-section-number">3</span>  Assumptions of ANOVA</a></li>
  <li><a href="#identifying-which-levels-are-different" id="toc-identifying-which-levels-are-different" class="nav-link" data-scroll-target="#identifying-which-levels-are-different"><span class="toc-section-number">4</span>  Identifying which levels are different</a>
  <ul class="collapse">
  <li><a href="#bonferroni" id="toc-bonferroni" class="nav-link" data-scroll-target="#bonferroni"><span class="toc-section-number">4.1</span>  Bonferroni</a></li>
  <li><a href="#tukeys-hsd" id="toc-tukeys-hsd" class="nav-link" data-scroll-target="#tukeys-hsd"><span class="toc-section-number">4.2</span>  Tukey’s HSD</a></li>
  <li><a href="#assumptions-of-the-post-hoc-test" id="toc-assumptions-of-the-post-hoc-test" class="nav-link" data-scroll-target="#assumptions-of-the-post-hoc-test"><span class="toc-section-number">4.3</span>  Assumptions of the post hoc test</a></li>
  </ul></li>
  <li><a href="#another-working-example" id="toc-another-working-example" class="nav-link" data-scroll-target="#another-working-example"><span class="toc-section-number">5</span>  Another working example</a></li>
  <li><a href="#two-way-anova" id="toc-two-way-anova" class="nav-link" data-scroll-target="#two-way-anova"><span class="toc-section-number">6</span>  Two-way ANOVA</a>
  <ul class="collapse">
  <li><a href="#checking-for-interaction-non-additive-model" id="toc-checking-for-interaction-non-additive-model" class="nav-link" data-scroll-target="#checking-for-interaction-non-additive-model"><span class="toc-section-number">6.1</span>  Checking for interaction (non-additive model)</a></li>
  <li><a href="#extracting-effects-for-each-level" id="toc-extracting-effects-for-each-level" class="nav-link" data-scroll-target="#extracting-effects-for-each-level"><span class="toc-section-number">6.2</span>  Extracting effects for each level</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="toc-section-number">7</span>  References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ANOVA</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><em>Last modified on 2023-04-06</em></p>
<div class="cell">

</div>
<div class="cell">

</div>
<hr>
<p>Package used in this tutorial:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr) <span class="co"># Used to reshape a data table</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Analysis of Variance (ANOVA) seeks to compare the means between two or more batches of numbers. You can think of an ANOVA as an extension of the t-test where three or more batches need to be compared. The name may seem misleading since it suggests that we are comparing variances and not some central value, but in fact, we compare the variances (spreads) between batches to assess if the central values are significantly different from one another. For example, let’s compare the following batches of numbers:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-2-1.png" width="480"></p>
</div>
</div>
<p>Given the very small overlap in spread between batch 2 and the two other batches, it’s obvious that batch 2 is significantly different from batches 1 and 3, but can we say with a similar level of certainty that batch 1 is significantly different from batch 3? Probably not, the slight offset in spread between batch 1 and 3 may be due to chance alone.</p>
<p>A one-way ANOVA compares measurement means between a single group of levels or batches. ANOVAs can be extended to include multiple groups (each having different levels). An ANOVA that compares means between two groups (each having their own set of levels) is referred to a two-way ANOVA.</p>
</section>
<section id="how-a-one-way-anova-is-calculated" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> How a one-way ANOVA is calculated</h1>
<p>This section focuses on one group of levels (hence a one-way ANOVA).</p>
<section id="the-variance-ratio-method" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-variance-ratio-method"><span class="header-section-number">2.1</span> The variance-ratio method</h2>
<p>An ANOVA test seeks to compare the spread between the batches (technically referred to as <em>levels</em>).</p>
<p>The first step is to sum the square of the <em>distances</em> between each value (from all levels) to the <em>grand</em> mean computed from <em>all</em> values (plotted as a dark dashed line in the following graphic). We’ll call this value the <em>total sum of squares</em> for the mean (<span class="math inline">\(SSE_{mean}\)</span>). It’s calculated as follows:</p>
<p><span class="math display">\[
SSE_{mean} = \sum (y - \bar{\bar y})^2
\]</span></p>
<div class="cell">

</div>
<p>where <span class="math inline">\(\bar{\bar{y}}\)</span> is the mean for <em>all</em> values. In this example, <span class="math inline">\(\bar{\bar y}\)</span> equals 24.7. In the following plot, we spread out the values in each level (for clarity) and measure their distances to the grand mean. Each level is assigned a unique color to distinguish the different batches.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-4-1.png" width="480"></p>
</div>
</div>
<p>Next, we compare the values in each level to their respective level means. Similar to the way we compute the <span class="math inline">\(SSE_{mean}\)</span>, we sum the squared differences for each level as follows:</p>
<p><span class="math display">\[
SSE = \sum (y_{batch1} - \bar y_{batch1})^2 + \sum (y_{batch2} - \bar y_{batch2})^2 + \sum (y_{batch3} - \bar y_{batch3})^2
\]</span></p>
<p>Where <span class="math inline">\(SSE\)</span> is the <strong>error sum of squares</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-5-1.png" width="480"></p>
</div>
</div>
<p>If the mean values of all three levels are the same, their horizontal lines should line up with the grand mean and both <span class="math inline">\(SSE_{mean}\)</span> and <span class="math inline">\(SSE\)</span> should be equal, if not, <span class="math inline">\(SSE\)</span> will be less than <span class="math inline">\(SSE_{mean}\)</span> (the distance between the points and their respective level mean will always be equal or shorter than their distances to the overall mean). The difference between <span class="math inline">\(SSE_{mean}\)</span> and <span class="math inline">\(SSE\)</span> is called the <strong>treatment sum of squares</strong> (also referred to as the <strong>model sum of squares</strong>):</p>
<p><span class="math display">\[
SSR = SSE_{mean} - SSE
\]</span></p>
<p>If SSR is close to 0, then the differences between the levels is small, if SSR is large, then two or more of the levels are significantly different from one another. SSR is, in fact, the squared difference between each group’s mean and the grand mean. Think of two competing models to predict the observed values: the grand mean, and each level’s mean. If the level means are close to the grand mean, then both the level means and grand mean will generate the same expected values. If they are different, then they will generate different expected values. So the greater the SSR, the more different the predicted values (and therefore the more different the means).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-6-1.png" width="480"></p>
</div>
</div>
<p>The goal is to compare the variability in <span class="math inline">\(SSE\)</span> to that in <span class="math inline">\(SSR\)</span>, however, <span class="math inline">\(SSR\)</span> can take on much larger values than <span class="math inline">\(SSA\)</span> (because <span class="math inline">\(SSR\)</span> is measuring from the group means and not the individual values). To remedy this bias, we compute the <strong>mean squares</strong> from both values by dividing the sum of squares by the <strong>degrees of freedom</strong>. For <span class="math inline">\(SSR\)</span>, this gives us: <span class="math display">\[
MSR = \frac{SSR}{p-1}
\]</span></p>
<p>where <span class="math inline">\(MSR\)</span> is the <strong>mean square for treatments</strong> (or <strong>mean square for model</strong>), and <span class="math inline">\(p\)</span> is the number of levels (3 in this example).</p>
<p>Likewise, we can compute the <strong>mean square for error</strong> as:</p>
<p><span class="math display">\[
MSE = \frac{SSE}{n-p}
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the total number of observations.</p>
<p>Next, we compute the <span class="math inline">\(F\)</span>-statistic (or <span class="math inline">\(F\)</span>-ratio) as:</p>
<p><span class="math display">\[
F = \frac{MSR}{MSE}
\]</span></p>
<p><span class="math inline">\(F\)</span> gives us the proportion of the overall spread in the measurements that can be explained by the levels vs.&nbsp;the proportion of the overall spread in the measurements <em>not</em> explained by the levels. A value of <span class="math inline">\(F\)</span> that approaches <span class="math inline">\(1\)</span> indicates that little to none of the variability in the measurements can be explained by the levels suggesting that differences in their mean may be due to random noise only. If <span class="math inline">\(F\)</span> is much larger than one, then the spreads between levels are quite different (meaning that these differences are large contributors to the overall spread) suggesting that the observed differences in mean values are significant too.</p>
<p>The following graphic shows the spread for <em>all</em> values in the data (right-side plot) and its spread broken down by levels (left-side plot). In this case, it seems that a good chunk of the overall spread can be explained by the differences in spread between levels. If this is still unclear, picture the plots with the measurements for batch 2 removed; what you would note is that the overall spread will be noticeably reduced suggesting that the measurements in level two alone were an important contributor to the overall spread.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-7-1.png" width="672"></p>
</div>
</div>
<p>Contrast this last example with the following dataset where the differences in spread (and mean) between levels are negligible. Removing anyone of the batches from the dataset would have a negligible impact on the overall spread in the measurements. We would say that little of the spread (variability) in the overall measurements can be explained by differences in measurements between levels; this would result in an <span class="math inline">\(F\)</span>-ratio close to <span class="math inline">\(1\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-8-1.png" width="672"></p>
</div>
</div>
<p>To assess whether a value of <span class="math inline">\(F\)</span> is significantly greater than 1, we must compare our observed <span class="math inline">\(F\)</span> to a distribution of <span class="math inline">\(F\)</span>’s we would expect to get if the means between levels were <em>not</em> different (we refer to the hypothesized <span class="math inline">\(F\)</span> values as <span class="math inline">\(F_{Ho}\)</span>).</p>
<p>In the following plot, a hypothetical <span class="math inline">\(F\)</span> ratio (plotted as a vertical red line) is located to the right of the distribution of <span class="math inline">\(F_{Ho}\)</span> values (delineated in a black line in the following plot). The shaded pink area to the right of the hypothetical <span class="math inline">\(F\)</span> represents the fraction of <span class="math inline">\(F_{Ho}\)</span> that would be more extreme than our observed <span class="math inline">\(F\)</span>. The goal is to assess whether or not we feel comfortable in concluding that our observed <span class="math inline">\(F\)</span> is significantly different from an <span class="math inline">\(F\)</span> we would expect to get if the means between batches were all the same.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-9-1.png" width="672"></p>
</div>
</div>
</section>
<section id="an-example-in-r" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="an-example-in-r"><span class="header-section-number">2.2</span> An example in R</h2>
<p>In this working example, we compare fecal coliform counts (represented as the log10 of organisms per 100 ml) in the Illinois River between seasons (summer, fall, winter and spring) across six years (data from Millard and Neerchal, 2001).</p>
<table class="table">
<thead>
<tr class="header">
<th>Year</th>
<th>Summer</th>
<th>Fall</th>
<th>Winter</th>
<th>Spring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1971</td>
<td>2.00</td>
<td>1.45</td>
<td>1.45</td>
<td>1.34</td>
</tr>
<tr class="even">
<td>1972</td>
<td>2.34</td>
<td>2.08</td>
<td>1.76</td>
<td>1.72</td>
</tr>
<tr class="odd">
<td>1973</td>
<td>2.48</td>
<td>2.32</td>
<td>2.08</td>
<td>2.04</td>
</tr>
<tr class="even">
<td>1974</td>
<td>2.63</td>
<td>2.45</td>
<td>2.36</td>
<td>2.15</td>
</tr>
<tr class="odd">
<td>1975</td>
<td>2.81</td>
<td>2.70</td>
<td>2.49</td>
<td>2.51</td>
</tr>
<tr class="even">
<td>1976</td>
<td>3.20</td>
<td>3.04</td>
<td>2.70</td>
<td>3.11</td>
</tr>
</tbody>
</table>
<p>Let’s first generate the data. We will create two data frames of the same data. One will be in a wide format, the other in a long format. We will use the former to generate a plot and the latter will be used in the ANOVA analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">Year =</span> <span class="fu">c</span>(<span class="dv">1971</span>,<span class="dv">1972</span>,<span class="dv">1973</span>,<span class="dv">1974</span>,<span class="dv">1975</span>,<span class="dv">1976</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Summer =</span> <span class="fu">c</span>(<span class="fl">2.00</span>, <span class="fl">2.34</span>, <span class="fl">2.48</span>, <span class="fl">2.63</span>, <span class="fl">2.81</span>, <span class="fl">3.20</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Fall =</span> <span class="fu">c</span>(<span class="fl">1.45</span>, <span class="fl">2.08</span>, <span class="fl">2.32</span>, <span class="fl">2.45</span>, <span class="fl">2.70</span>, <span class="fl">3.04</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Winter =</span> <span class="fu">c</span>(<span class="fl">1.45</span>, <span class="fl">1.76</span>, <span class="fl">2.08</span>, <span class="fl">2.36</span>, <span class="fl">2.49</span>, <span class="fl">2.70</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Spring =</span> <span class="fu">c</span>(<span class="fl">1.34</span>, <span class="fl">1.72</span>, <span class="fl">2.04</span>, <span class="fl">2.15</span>, <span class="fl">2.51</span>, <span class="fl">3.11</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># However, to run an ANOVA, the data needs to be in a long form</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>dat.long <span class="ot">&lt;-</span> <span class="fu">gather</span>(dat, <span class="at">key =</span> <span class="st">"Season"</span>, <span class="at">value=</span><span class="st">"Value"</span>, <span class="sc">-</span>Year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, let’s plot the points then add the grand mean (black line) and each season’s mean (red lines) to the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an empty plot</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( <span class="cn">NULL</span>, <span class="at">xlim=</span> <span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">4.5</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">3.5</span>), <span class="at">axes=</span><span class="cn">FALSE</span>, <span class="at">xlab=</span><span class="cn">NA</span>,<span class="at">ylab=</span><span class="st">"Fecal Coliform"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">box</span>()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">labels =</span> <span class="fu">names</span>(dat)[<span class="sc">-</span><span class="dv">1</span>], <span class="at">at=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">las=</span><span class="dv">2</span>, )</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(dat)), dat<span class="sc">$</span>Summer, <span class="at">pch=</span><span class="dv">1</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(<span class="dv">2</span>,<span class="fu">nrow</span>(dat)), dat<span class="sc">$</span>Fall, <span class="at">pch=</span><span class="dv">2</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(<span class="dv">3</span>,<span class="fu">nrow</span>(dat)), dat<span class="sc">$</span>Winter, <span class="at">pch=</span><span class="dv">3</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(<span class="dv">4</span>,<span class="fu">nrow</span>(dat)), dat<span class="sc">$</span>Spring, <span class="at">pch=</span><span class="dv">4</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the grand mean</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(dat.long<span class="sc">$</span>Value), <span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Add each group's mean</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(.<span class="dv">8</span>,<span class="fl">1.2</span>), <span class="fu">rep</span>(<span class="fu">mean</span>(dat<span class="sc">$</span>Summer),<span class="dv">2</span>), <span class="at">col=</span><span class="st">"red"</span> )</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="fl">1.8</span>,<span class="fl">2.2</span>), <span class="fu">rep</span>(<span class="fu">mean</span>(dat<span class="sc">$</span>Fall),<span class="dv">2</span>), <span class="at">col=</span><span class="st">"red"</span> )</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="fl">2.8</span>,<span class="fl">3.2</span>), <span class="fu">rep</span>(<span class="fu">mean</span>(dat<span class="sc">$</span>Winter),<span class="dv">2</span>), <span class="at">col=</span><span class="st">"red"</span> )</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="fl">3.8</span>,<span class="fl">4.2</span>), <span class="fu">rep</span>(<span class="fu">mean</span>(dat<span class="sc">$</span>Spring),<span class="dv">2</span>), <span class="at">col=</span><span class="st">"red"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-11-1.png" width="384"></p>
</div>
</div>
<p>A quick glance at the plot suggests that the variance within each season is large relative to the differences in means between each seasons. But could summer values be slightly higher than those of other seasons? We check this assumption with an ANOVA test.</p>
<section id="computing-anova-the-hard-way" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="computing-anova-the-hard-way"><span class="header-section-number">2.2.1</span> Computing ANOVA the hard way</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>SSE.m <span class="ot">&lt;-</span> <span class="fu">sum</span>( (dat.long<span class="sc">$</span>Value <span class="sc">-</span> <span class="fu">mean</span>(dat.long<span class="sc">$</span>Value))<span class="sc">^</span><span class="dv">2</span> ) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>( (dat<span class="sc">$</span>Summer <span class="sc">-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>Summer))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>            (dat<span class="sc">$</span>Fall <span class="sc">-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>Fall))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>            (dat<span class="sc">$</span>Winter <span class="sc">-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>Winter))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>            (dat<span class="sc">$</span>Spring <span class="sc">-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>Spring))<span class="sc">^</span><span class="dv">2</span> )  </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>SSR <span class="ot">&lt;-</span> SSE.m <span class="sc">-</span> SSE</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>MSR <span class="ot">&lt;-</span> SSR <span class="sc">/</span> <span class="dv">3</span>   <span class="co"># (p - 1) or 3 degrees of freedom</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSE <span class="sc">/</span> <span class="dv">20</span>  <span class="co"># (n - p) or 20 degrees of freedom</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>Fratio <span class="ot">&lt;-</span> MSR<span class="sc">/</span>MSE</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>p.val  <span class="ot">&lt;-</span> <span class="fu">pf</span>(Fratio, <span class="dv">3</span>, <span class="dv">20</span>,<span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function <code>pf()</code> compares our <span class="math inline">\(F\)</span>-ratio to the distribution of <span class="math inline">\(F_{Ho}\)</span> values one would expect to get if the means between seasons were not different. The two numbers following the <span class="math inline">\(F\)</span>-ratio value are the degrees of freedom for the <span class="math inline">\(MSR\)</span> and the <span class="math inline">\(MSE\)</span> calculated from <span class="math inline">\((p-1)\)</span> and <span class="math inline">\((n-p)\)</span> respectively.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-13-1.png" width="672"></p>
</div>
</div>
<p>The computed statistics are:</p>
<table class="table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SSE(mean)</td>
<td>6.11</td>
</tr>
<tr class="even">
<td>SSE</td>
<td>5.35</td>
</tr>
<tr class="odd">
<td>SSR</td>
<td>0.77</td>
</tr>
<tr class="even">
<td>MSR</td>
<td>0.26</td>
</tr>
<tr class="odd">
<td>MSE</td>
<td>0.27</td>
</tr>
<tr class="even">
<td>F</td>
<td>0.96</td>
</tr>
<tr class="odd">
<td>p</td>
<td>0.433</td>
</tr>
</tbody>
</table>
<p>Our calculated p-value is 0.433 indicating that about 43% of the <span class="math inline">\(F_{Ho}\)</span> values are more extreme than ours. So it would be unwise to dismiss the chance that the means between all four seasons are equal to one another.</p>
</section>
<section id="computing-anova-the-easy-way" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="computing-anova-the-easy-way"><span class="header-section-number">2.2.2</span> Computing ANOVA the easy way</h3>
<p>We can use the <code>anova</code> function to compute the <span class="math inline">\(F\)</span>-ratio and the <span class="math inline">\(p\)</span>-value. The function takes as argument a model (a linear regression model in this case) where the dependent variable <span class="math inline">\(y\)</span> is the measurement value and the independent variable <span class="math inline">\(x\)</span> is the level (or seasons in our example). This implementation of ANOVA requires that the season values be in one column (the <span class="math inline">\(x\)</span> column) and that the measurements be in another column (the <span class="math inline">\(y\)</span> column). This requires that we use the <em>long</em> version of our table, <code>dat.long</code>, where the <span class="math inline">\(x\)</span> column is labeled <code>Season</code> and the <span class="math inline">\(y\)</span> column is labeled <code>Value</code>. The first few rows of <code>dat.long</code> look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Year Season Value
1 1971 Summer  2.00
2 1972 Summer  2.34
3 1973 Summer  2.48
4 1974 Summer  2.63
5 1975 Summer  2.81
6 1976 Summer  3.20</code></pre>
</div>
</div>
<p>The ANOVA analysis is thus computed as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(Value <span class="sc">~</span> Season, dat.long))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Value
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Season     3 0.7666 0.25554  0.9556 0.4328
Residuals 20 5.3483 0.26741               </code></pre>
</div>
</div>
<p>The column <code>Mean Sq</code> displays the mean sum-of-squares for treatment <span class="math inline">\(SSR\)</span>, and the error sum-of-square, <span class="math inline">\(SSE\)</span>. The <span class="math inline">\(F\)</span>-ratio and <span class="math inline">\(p\)</span>-value are the same as those computed in the last subsection. Again, there is no evidence that the seasons have an influence on the mean concentrations of fecal coliform counts.</p>
</section>
<section id="anova-as-a-regression" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="anova-as-a-regression"><span class="header-section-number">2.2.3</span> ANOVA as a regression</h3>
<p>You’ll note that this approach in computing the ANOVA makes use of the linear regression function <code>lm</code>. This is because a one-way ANOVA is nothing more than a regression between all values in the batches and their levels expressed as categorical values where the number of categorical values is the number of levels minus <span class="math inline">\(1\)</span>. In essence the ANOVA is generating the following model:</p>
<p><span class="math inline">\(Coliform\ count = a + b(FALL) + c(Winter) + d(Spring)\)</span></p>
<p>So, if a value belongs to the FALL batch, the model looks like this:</p>
<p><span class="math inline">\(Coliform\ count = a + b(1) + c(0) + d(0)\)</span></p>
<p>If the value belongs to the SUMMER batch, the model looks like this:</p>
<p><span class="math inline">\(Coliform\ count = a + b(0) + c(0) + d(0)\)</span></p>
<p>where <span class="math inline">\(a\)</span> is the mean value for summer coliform measurements. It follows that the coefficients <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span> and <span class="math inline">\(d\)</span> are differences in mean values between summer measurements and fall, winter and spring measurements respectively:</p>
<p><span class="math inline">\(a\)</span> = <code>mean(dat$Summer)</code> = 2.58</p>
<p><span class="math inline">\(b\)</span> = <code>mean(dat$Fall) - mean(dat$Summer)</code> = -0.24</p>
<p><span class="math inline">\(c\)</span> = <code>mean(dat$Winter) - mean(dat$Summer)</code> = -0.44</p>
<p><span class="math inline">\(d\)</span> = <code>mean(dat$Spring) - mean(dat$Summer)</code> = -0.43</p>
<p>These coefficients can be extracted from the <code>lm</code> model via the <code>coefficients</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>( <span class="fu">lm</span>( Value <span class="sc">~</span> Season, dat.long) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) SeasonSpring SeasonSummer SeasonWinter 
   2.3400000   -0.1950000    0.2366667   -0.2000000 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Note that R has a built-in function called <code>aov()</code> that can be used in lieu of <code>lm()</code>. The computed model will be the same but the functions differ slightly in their methods. Examples of its use are presented later in the tutorial.</p>
</blockquote>
</section>
</section>
</section>
<section id="assumptions-of-anova" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Assumptions of ANOVA</h1>
<p>There are three assumptions that should be met when computing an ANOVA:</p>
<ol type="1">
<li>The response variable must be quantitative (i.e.&nbsp;measured on a continuous scale). It should not be a count (i.e.&nbsp;the result of qualitative outcome such as yes/no).</li>
<li>The variance between the batches (homogeneity of variance) should be similar.</li>
<li>Observations should be independent of one another.</li>
<li>The distribution of values within each group should be normally distributed. If a transformation is applied to the data, it should be applied to <em>all</em> batches. Note that the distribution of values for all combined batches need not be normally distributed.</li>
</ol>
<p>You can check these assumptions graphically by plotting the results of the ANOVA analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>OP <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(Value <span class="sc">~</span> Season, dat.long), <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(OP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-17-1.png" width="576"></p>
</div>
</div>
<p>The <em>Residuals-Fit</em> plot checks that the variance is constant across groups. What you want to avoid is a funnel like shape to the data (which may be present in this example). The <em>Normal Q-Q</em> plot checks for normality in the residuals–the closer the points fit the diagonal line, the better.</p>
<p>If normality in the residuals seems to be an issue, then you might want to consider re-expressing your data (note that we already re-expressed the coliform count by logging its values–had he worked with the original data the assumption of normality would have been violated).</p>
<p>If the assumption of equal variance is violated, you might want to run the analysis using <code>oneway.test()</code> (which applies <strong>Welch’s F</strong> to the data):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oneway.test</span>(Value <span class="sc">~</span> Season, dat.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One-way analysis of means (not assuming equal variances)

data:  Value and Season
F = 1.092, num df = 3.000, denom df = 10.998, p-value = 0.3931</code></pre>
</div>
</div>
<p>Note the slightly higher F-value and p-value (but not enough to change the analysis outcome)</p>
</section>
<section id="identifying-which-levels-are-different" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Identifying which levels are different</h1>
<p>So far, we have seen that the ANOVA test tells us if the means between batches (levels) are similar, but it does not tell us <em>which</em> batch(es) of numbers may be different. One approach in assessing which level(s) is(are) significantly different from the mean is to implement a <strong>post hoc</strong> procedure (aka <strong>pairwise comparison</strong>).</p>
<p>There are many <em>post hoc</em> procedures to choose from. Two popular methods are presented here: the <strong>Bonferroni</strong> procedure and <strong>Tukey’s HSD</strong> procedure. Both tend to generate slightly different results depending on the data characteristics. It’s therefore worthwhile to run both to assess if the levels are significantly different from one another. But note that in many cases there is no substitute for a visual assessment of the differences between batches.</p>
<section id="bonferroni" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="bonferroni"><span class="header-section-number">4.1</span> Bonferroni</h2>
<p>The Bonferroni method can be implemented using the <code>pairwise.t.test</code> function with the first two parameters pointing to the column of values and the column of variables respectively, and the third parameter pointing to the pairwise method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>( dat.long<span class="sc">$</span>Value, dat.long<span class="sc">$</span>Season, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  dat.long$Value and dat.long$Season 

       Fall Spring Summer
Spring 1.00 -      -     
Summer 1.00 0.98   -     
Winter 1.00 1.00   0.95  

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>The output is a matrix of <span class="math inline">\(p\)</span>-values for different pairs of levels (Fall-Summer, Winter-Summer, etc…). A low <span class="math inline">\(P\)</span>-value indicates significant differences between levels. In our working example, all <span class="math inline">\(P\)</span>-values are relatively high indicating that the means between levels are not statistically significant.</p>
</section>
<section id="tukeys-hsd" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="tukeys-hsd"><span class="header-section-number">4.2</span> Tukey’s HSD</h2>
<p>The Tukey method is implemented using the <code>TukeyHSD</code> method. The first parameter is an <code>aov</code> object (<code>aov</code> is nearly identical to the <code>anova(lm(...))</code> method used thus far), and the second variable is the <em>levels</em> column from the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>( <span class="fu">aov</span>( Value <span class="sc">~</span> Season, dat.long), <span class="st">"Season"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Value ~ Season, data = dat.long)

$Season
                    diff        lwr       upr     p adj
Spring-Fall   -0.1950000 -1.0306503 0.6406503 0.9132083
Summer-Fall    0.2366667 -0.5989836 1.0723170 0.8569058
Winter-Fall   -0.2000000 -1.0356503 0.6356503 0.9071983
Summer-Spring  0.4316667 -0.4039836 1.2673170 0.4870045
Winter-Spring -0.0050000 -0.8406503 0.8306503 0.9999983
Winter-Summer -0.4366667 -1.2723170 0.3989836 0.4773334</code></pre>
</div>
</div>
<p>The Tukey method generates a table of <span class="math inline">\(P\)</span>-values (as opposed to a matrix) for all pairs of levels. Note the slightly lower <span class="math inline">\(P\)</span>-values than those generated with the Bonferroni method. The Tukey HSD method tends to be more conservative than the Bonferri method and is thus more likely to reject the null hypothesis (that the means are equal) than the Bonferri method. This comes with an advantage, however, in that the Tukey test tends to have greater statistical <em>power</em> when there are many different levels (or batches) in our dataset.</p>
<p>The Tukey test also generates the 95% confidence intervals (<code>lwr</code> = lower bound and <code>upr</code> = upper bound). If the lower bound is less than <span class="math inline">\(0\)</span> and the upper bound is greater than <span class="math inline">\(0\)</span> we cannot say that the means between both levels are not significantly different at a confidence level of 0.05.</p>
</section>
<section id="assumptions-of-the-post-hoc-test" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="assumptions-of-the-post-hoc-test"><span class="header-section-number">4.3</span> Assumptions of the post hoc test</h2>
<p>The <em>post</em> hoc procedure assumes that we are only interested in knowing which effect (if any) is different from the grand mean. It makes no assumption about the direction of this difference (i.e.&nbsp;if the level mean is greater than or less than the overall mean). This is analogous to implementing a two-tailed test.</p>
<p>If knowing whether the effect mean is greater than or less than the overall mean, a <strong>planned contrast</strong> procedure (aka <strong>planned comparison</strong> procedure) should be adopted instead. This procedure is not covered in this tutorial, but can be found in most introductory stats books.</p>
</section>
</section>
<section id="another-working-example" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Another working example</h1>
<p>The coliform dataset was an example of effects that did not differ. Here, we’ll look at an example with differences in effect means. We’ll use a dataset that comes installed with <code>R</code>, the <code>ChickWeight</code> data. This dataset tracks the weights of chicks using different diet types. We will grab a subset of the data and only focus on day 21 measurements. We will also restrict the columns to <code>Weight</code> and <code>Diet</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> ChickWeight[ChickWeight<span class="sc">$</span>Time<span class="sc">==</span><span class="dv">21</span>,<span class="fu">c</span>(<span class="st">"weight"</span>, <span class="st">"Diet"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The group column is <code>Diet</code> which has four levels. These levels are identified as numbers (<span class="math inline">\(1\)</span> through <span class="math inline">\(4\)</span>). One needs to be careful when running an ANOVA using levels encoded as numbers since the <code>lm</code> model may interpret such values as continuous and not categorical. It’s therefore good practice to force the numbers as <code>factors</code> by using the <code>as.factor</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dat2<span class="sc">$</span>Diet <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dat2<span class="sc">$</span>Diet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that in this particular case, the conversion was not necessary since the <code>chickweight</code> table from which we extracted the values stored the <code>Diet</code> field as a factor (and this attribute was carried over to our <code>dat</code> data frame).</p>
<p>Next, let’s plot the points along with the grand mean (dashed line) and each levels’ mean value (symbolized as a filled circle).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(weight <span class="sc">~</span> <span class="fu">as.numeric</span>(Diet), dat2, <span class="at">col=</span>Diet, <span class="at">pch=</span><span class="dv">3</span>,<span class="at">cex=</span>.<span class="dv">6</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>( <span class="at">h =</span> <span class="fu">mean</span>(dat2<span class="sc">$</span>weight), <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>( <span class="fu">unique</span>(dat2<span class="sc">$</span>Diet) , <span class="fu">by</span>(dat2<span class="sc">$</span>weight, dat2[,<span class="st">"Diet"</span>], mean) , <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col=</span><span class="fu">unique</span>(dat2<span class="sc">$</span>Diet))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-23-1.png" width="384"></p>
</div>
</div>
<p>One level, diet 3, seems to be a bit different from the others, but we will need to run and ANOVA to make sure of this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(weight <span class="sc">~</span> Diet, dat2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: weight
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
Diet       3  57164 19054.7  4.6547 0.006858 **
Residuals 41 167839  4093.6                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The small <span class="math inline">\(p\)</span>-value suggests that not all levels have the same mean value. We can run a <em>post hoc</em> test to identify which level may be different</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>( dat2<span class="sc">$</span>weight, dat2<span class="sc">$</span>Diet, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  dat2$weight and dat2$Diet 

  1      2      3     
2 0.9573 -      -     
3 0.0053 0.3533 -     
4 0.1669 1.0000 1.0000

P value adjustment method: bonferroni </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>( <span class="fu">aov</span>( weight <span class="sc">~</span> Diet, dat2), <span class="st">"Diet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = weight ~ Diet, data = dat2)

$Diet
         diff        lwr       upr     p adj
2-1  36.95000  -32.11064 106.01064 0.4868095
3-1  92.55000   23.48936 161.61064 0.0046959
4-1  60.80556  -10.57710 132.18821 0.1192661
3-2  55.60000  -21.01591 132.21591 0.2263918
4-2  23.85556  -54.85981 102.57092 0.8486781
4-3 -31.74444 -110.45981  46.97092 0.7036249</code></pre>
</div>
</div>
<p>Both tests suggest that diet 3 is significantly different from diet 1, but the differences between the other levels are not significant.</p>
</section>
<section id="two-way-anova" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Two-way ANOVA</h1>
<p>A two-way ANOVA adds another factor (explanatory variable) to the analysis. For example, in the earlier fecal coliform count dataset (Section 2.2), coliform counts were only compared across season yet, another piece of information is made available to us: year. We could choose to treat year as a second factor. This would add a <em>second</em> hypothesis to our analysis, that being <em>“can <strong>year</strong> help explain the variability in coliform count”</em> (the first hypothesis asks if seasons can explain the variability in the coliform count).</p>
<p>While a one-way ANOVA does not make sense if the data are devoid of replicates, a two-way ANOVA can be conducted if the data do not have replicates (referred to as an <strong>unreplicated two-way ANOVA</strong>). The implementation does not differ between both scenarios except when testing for interaction (described further below).</p>
<p>The <code>dat.long</code> dataframe is a <em>replicatless</em> dataset. What follows is a <em>replicated</em> version of the dataset (used later in demonstrating for interactions). Note that this dataset is used for instructional purposes only and is <em>not</em> the way you would create replicate measurements!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">321</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>datr.long <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">Year   =</span> <span class="fu">rep</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">1971</span>,<span class="dv">1972</span>,<span class="dv">1973</span>,<span class="dv">1974</span>,<span class="dv">1975</span>,<span class="dv">1976</span>),<span class="at">each=</span><span class="dv">3</span>),<span class="dv">4</span>),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Season =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Summer"</span>,<span class="st">"Fall"</span>,<span class="st">"Winter"</span>,<span class="st">"Spring"</span>),<span class="at">each=</span><span class="dv">18</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Value  =</span> <span class="fu">rep</span>(dat.long<span class="sc">$</span>Value,<span class="at">each=</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">72</span>,<span class="dv">0</span>,<span class="fl">0.1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the following examples, we will use the <code>dat.long</code> dataset but note that the same code chunks can be applied to the <code>datr.long</code> dataset.</p>
<p>First we’ll visualize the variability across each factor via boxplots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Value <span class="sc">~</span> Year, dat.long)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Value <span class="sc">~</span> Season, dat.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-27-1.png" width="672"></p>
</div>
</div>
<p>The differences in (logged) coliform counts across years appear significant from the plots. More so than the differences across seasons.</p>
<p>A two-way ANOVA test assesses how much of an effect (if any) each factor has on the variable. The implementation in R is simple–just add the <code>Year</code> variable to the one-way ANOVA function shown in Section 2.2.2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(Value <span class="sc">~</span> Season <span class="sc">+</span> <span class="fu">as.factor</span>(Year), dat.long))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Value
                Df Sum Sq Mean Sq F value          Pr(&gt;F)    
Season           3 0.7666 0.25554  17.574 0.0000357897957 ***
as.factor(Year)  5 5.1302 1.02603  70.562 0.0000000006975 ***
Residuals       15 0.2181 0.01454                            
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Note that we are wrapping the <code>Year</code> variable with the <code>as.factor</code> function to force R to treat that variable as a factor and not a continuous variable (it’s currently stored in R as a <code>numeric</code> and <em>not</em> a <code>factor</code>).</p>
<p>The p-values appear significant for <em>both</em> factors (you’ll recall that an earlier one-way analysis suggested that seasons had little influence on the variability on coliform counts). This discrepancy can be partially explained by looking at a boxplot of the <em>residuals</em> vs.&nbsp;<code>Season</code> (i.e.&nbsp;the residuals that remain after accounting for <code>Year</code> alone in the model).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="fu">lm</span>(Value <span class="sc">~</span> <span class="fu">as.factor</span>(Year), dat.long))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(res <span class="sc">~</span> dat.long<span class="sc">$</span>Season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-29-1.png" width="288"></p>
</div>
</div>
<p>Accounting for variability across years reveals a greater spread in values across seasons (hence the drop in that factor’s p-value in a two-way analysis).</p>
<p>The two-factor model coefficients can be extracted as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(<span class="fu">lm</span>(Value <span class="sc">~</span> Season <span class="sc">+</span> <span class="fu">as.factor</span>(Year), dat.long))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)        SeasonSpring        SeasonSummer        SeasonWinter as.factor(Year)1972 as.factor(Year)1973 
          1.5995833          -0.1950000           0.2366667          -0.2000000           0.4150000           0.6700000 
as.factor(Year)1974 as.factor(Year)1975 as.factor(Year)1976 
          0.8375000           1.0675000           1.4525000 </code></pre>
</div>
</div>
<p>The model is thus,</p>
<p><span class="math inline">\(Coliform_{log} = 1.60 - 0.19 Spring +0.24 Summer -0.20 Winter + \\ 0.42 Year_{1972} +0.67 Year_{1973} +0.840 Year_{1974} + 1.07 Year_{1975} + 1.45 Year_{1976}\)</span></p>
<p>So if we want to predict (log) Coliform counts for the Fall season of 1976, the model would take the form:</p>
<p><span class="math inline">\(Coliform_{log} = 1.60 - 0.19(0) +0.24(0) -0.20(0) + 0.42 (0) + 0.67(0) +0.840(0) + 1.07(0) + 1.45(1)\)</span></p>
<p>or</p>
<p><span class="math inline">\(Coliform_{log} = 1.60 + 1.45(1)\)</span></p>
<p>Note that the Fall coefficient, like the 1971 coefficient, is wrapped in the intercept term.</p>
<section id="checking-for-interaction-non-additive-model" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="checking-for-interaction-non-additive-model"><span class="header-section-number">6.1</span> Checking for interaction (non-additive model)</h2>
<blockquote class="blockquote">
<p>Note that it makes no sense to test for interactivity if you do not have replicates (i.e.&nbsp;if you have just one case per factor level combinations) since you may not be able to distinguish the error terms from the residuals. In the examples that follow, we’ll make use of the <code>datr.long</code> dataset which <em>has</em> (simulated) replicates.</p>
</blockquote>
<p>We need to check that the additive model we’ve chosen is appropriate for this dataset. A graphical approach involves plotting the values as a function of one factor using a line graph (where each line represents the levels of the other factor). This is sometimes referred to as an <em>interactive plot</em>. We’ll make use of the built-in <code>interaction.plot</code> function where one of the factors (<code>Year</code>) will be mapped to the x-axis and the other factor (<code>Season</code>) will be mapped to the line plots. This function does not have a <code>data=...</code> parameter telling it which data frame to work off of so we’ll wrap the function with the <code>with()</code> function which defines the data frame from which the variables are to be read from.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(datr.long, <span class="fu">interaction.plot</span>(<span class="fu">as.factor</span>(Year), Season, Value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ANOVA_files/figure-html/unnamed-chunk-31-1.png" width="480"></p>
</div>
</div>
<p>We are seeking parallel lines. The more <em>non-parallel</em> the lines, the more unlikely an additive model is a proper fit. If the lines are clearly not parallel, then there is interaction between the factors and an interaction term is probably needed in the model. If we chose to add an interaction component to our model, we would simply augment the formula by adding <code>as.factor(Year):Season</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(Value <span class="sc">~</span> Season <span class="sc">+</span> <span class="fu">as.factor</span>(Year) <span class="sc">+</span> <span class="fu">as.factor</span>(Year)<span class="sc">:</span>Season, datr.long))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Value
                       Df  Sum Sq Mean Sq  F value                Pr(&gt;F)    
Season                  3  2.6276 0.87588  86.9506 &lt; 0.00000000000000022 ***
as.factor(Year)         5 14.9474 2.98948 296.7720 &lt; 0.00000000000000022 ***
Season:as.factor(Year) 15  0.6324 0.04216   4.1856            0.00007479 ***
Residuals              48  0.4835 0.01007                                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value associated with the interactive term <code>as.factor(Year):Season</code> is small suggesting that the interaction should not be ignored. Note that had the two-way ANOVA been run on the replicate-free version of the data (<code>dat.long</code>), the code chunk would not have generated p-values.</p>
<p>Coefficients can be extracted using the <code>coefficients()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(<span class="fu">lm</span>(Value <span class="sc">~</span> Season <span class="sc">+</span> <span class="fu">as.factor</span>(Year) <span class="sc">+</span> <span class="fu">as.factor</span>(Year)<span class="sc">:</span>Season, datr.long))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     (Intercept)                     SeasonSpring                     SeasonSummer 
                     1.514706536                     -0.219142681                      0.509122788 
                    SeasonWinter              as.factor(Year)1972              as.factor(Year)1973 
                    -0.089699659                      0.558927966                      0.705495273 
             as.factor(Year)1974              as.factor(Year)1975              as.factor(Year)1976 
                     0.896043592                      1.169276817                      1.564987568 
SeasonSpring:as.factor(Year)1972 SeasonSummer:as.factor(Year)1972 SeasonWinter:as.factor(Year)1972 
                    -0.055451015                     -0.241938153                     -0.271609111 
SeasonSpring:as.factor(Year)1973 SeasonSummer:as.factor(Year)1973 SeasonWinter:as.factor(Year)1973 
                     0.131119255                     -0.206021571                     -0.007361442 
SeasonSpring:as.factor(Year)1974 SeasonSummer:as.factor(Year)1974 SeasonWinter:as.factor(Year)1974 
                    -0.119064438                     -0.247193634                      0.090749725 
SeasonSpring:as.factor(Year)1975 SeasonSummer:as.factor(Year)1975 SeasonWinter:as.factor(Year)1975 
                     0.050233770                     -0.333834613                     -0.129534625 
SeasonSpring:as.factor(Year)1976 SeasonSummer:as.factor(Year)1976 SeasonWinter:as.factor(Year)1976 
                     0.165218848                     -0.386425892                     -0.317247156 </code></pre>
</div>
</div>
<p>Note that one disadvantage in having so many terms in the model is that you reduce the <em>power</em> of the model. In this example we now have 23 variables and a little more than three times as many measurements (72 to be exact). It’s always good practice to seek the most parsimonious model possible. This may involve, for example, grouping factor levels if theory supports it.</p>
</section>
<section id="extracting-effects-for-each-level" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="extracting-effects-for-each-level"><span class="header-section-number">6.2</span> Extracting effects for each level</h2>
<p>The regression model will wrap one level’s effect from each factor into the intercept term however, you might wish to know each level’s effect on the measured variable. This requires decomposing the model’s intercept into an overall mean measurement and two level effects (one for each factor). This can be done by running the ANOVA analysis using <code>aov()</code> then wrapping its output with the <code>model.tables()</code> function as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Value <span class="sc">~</span> Season <span class="sc">+</span> <span class="fu">as.factor</span>(Year), dat.long)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model.tables</span>(M1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tables of effects

 Season 
Season
    Fall   Spring   Summer   Winter 
 0.03958 -0.15542  0.27625 -0.16042 

 as.factor(Year) 
as.factor(Year)
   1971    1972    1973    1974    1975    1976 
-0.7404 -0.3254 -0.0704  0.0971  0.3271  0.7121 </code></pre>
</div>
</div>
<p>The overall mean (and new model intercept) can be extracted from the original table as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dat.long<span class="sc">$</span>Value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.300417</code></pre>
</div>
</div>
<p>While this approach expands the model by adding two more variables, it does allow one to quantify the effect each level has in explaining the coliform counts. For example, the model suggests that the overall mean (log) coliform count is <code>2.3</code> but the Spring seasons lower that value by about <code>-0.155</code>. Likewise, we can state that the year 1975 increases the overall mean by about <code>0.327</code>. It’s also clear from the output that 1971 had the greatest effect on coliform count by dropping the overall value by <code>-0.7404</code>.</p>
<p>Note, however, that if the model has a significant cross-factor interaction effect, you should not attempt to draw anything too meaningful from the main level effects. In such a scenario, the most meaningful result to glean from the model is the interaction between the factors.</p>
</section>
</section>
<section id="references" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References</h1>
<p>Millard S.P, Neerchal N.K., <em>Environmental Statistics with S-Plus</em>, 2001.<br>
McClave J.T., Dietrich F.H., <em>Statistics</em>, 4th edition, 1988.<br>
Vik P., <em>Regression, ANOVA, and the General Linear Model: A Statistics Primer</em>, 2013.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-right">Creative Commons License, Manny Gimond, 2022</div>
  </div>
</footer>



</body></html>