<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Basic stats explained (in R) - Comparing means: z and t tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Basic stats explained (in R)</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./CI.html">Confidence intervals</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./z_t_tests.html" aria-current="page">Z and T tests</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./F_test.html">F-test: Test for difference in spread</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ChiSquare_test.html">ChiSquare</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./regression.html">Ordinary least squares Regression</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ANOVA.html">Analysis of variance (ANOVA)</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Logistic.html">Logistic regression</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tests-of-significance-single-sample-inference" id="toc-tests-of-significance-single-sample-inference" class="nav-link active" data-scroll-target="#tests-of-significance-single-sample-inference"> <span class="header-section-number">1</span> Tests of Significance (single sample inference)</a>
  <ul class="collapse">
  <li><a href="#the-null-and-the-alternative-hypotheses" id="toc-the-null-and-the-alternative-hypotheses" class="nav-link" data-scroll-target="#the-null-and-the-alternative-hypotheses"> <span class="header-section-number">1.1</span> The null and the alternative hypotheses</a></li>
  <li><a href="#test-statistics" id="toc-test-statistics" class="nav-link" data-scroll-target="#test-statistics"> <span class="header-section-number">1.2</span> Test statistics</a></li>
  <li><a href="#z-tests" id="toc-z-tests" class="nav-link" data-scroll-target="#z-tests"> <span class="header-section-number">1.3</span> <span class="math inline">\(z\)</span>-tests</a></li>
  <li><a href="#t-tests" id="toc-t-tests" class="nav-link" data-scroll-target="#t-tests"> <span class="header-section-number">1.4</span> <span class="math inline">\(t\)</span>-tests</a></li>
  <li><a href="#follow-up-examples" id="toc-follow-up-examples" class="nav-link" data-scroll-target="#follow-up-examples"> <span class="header-section-number">1.5</span> Follow-up examples</a>
  <ul class="collapse">
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link" data-scroll-target="#problem-1"> <span class="header-section-number">1.5.1</span> Problem 1</a></li>
  <li><a href="#solution-to-problem-1" id="toc-solution-to-problem-1" class="nav-link" data-scroll-target="#solution-to-problem-1"> <span class="header-section-number">1.5.2</span> Solution to problem 1</a></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2"> <span class="header-section-number">1.5.3</span> Problem 2</a></li>
  <li><a href="#solution-to-problem-2" id="toc-solution-to-problem-2" class="nav-link" data-scroll-target="#solution-to-problem-2"> <span class="header-section-number">1.5.4</span> Solution to problem 2</a></li>
  </ul></li>
  <li><a href="#using-the-built-in-t.test-function" id="toc-using-the-built-in-t.test-function" class="nav-link" data-scroll-target="#using-the-built-in-t.test-function"> <span class="header-section-number">1.6</span> Using the built in <strong>t.test</strong> function</a></li>
  </ul></li>
  <li><a href="#tests-of-significance-two-independent-samples-comparison" id="toc-tests-of-significance-two-independent-samples-comparison" class="nav-link" data-scroll-target="#tests-of-significance-two-independent-samples-comparison"> <span class="header-section-number">2</span> Tests of Significance (two independent samples comparison)</a>
  <ul class="collapse">
  <li><a href="#z-test-with-two-samples-large-sample-sizes" id="toc-z-test-with-two-samples-large-sample-sizes" class="nav-link" data-scroll-target="#z-test-with-two-samples-large-sample-sizes"> <span class="header-section-number">2.1</span> <span class="math inline">\(z\)</span> test with two samples (large sample sizes)</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"> <span class="header-section-number">2.1.1</span> Example</a></li>
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution"> <span class="header-section-number">2.1.2</span> Solution</a></li>
  </ul></li>
  <li><a href="#t-test-with-two-samples-small-sample-sizes" id="toc-t-test-with-two-samples-small-sample-sizes" class="nav-link" data-scroll-target="#t-test-with-two-samples-small-sample-sizes"> <span class="header-section-number">2.2</span> <span class="math inline">\(t\)</span> test with two samples (small sample sizes )</a>
  <ul class="collapse">
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"> <span class="header-section-number">2.2.1</span> Example</a></li>
  <li><a href="#solution-1" id="toc-solution-1" class="nav-link" data-scroll-target="#solution-1"> <span class="header-section-number">2.2.2</span> Solution</a></li>
  </ul></li>
  <li><a href="#notes-on-z-and-t-tests" id="toc-notes-on-z-and-t-tests" class="nav-link" data-scroll-target="#notes-on-z-and-t-tests"> <span class="header-section-number">2.3</span> Notes on z and t tests</a>
  <ul class="collapse">
  <li><a href="#assumption-of-equal-variance" id="toc-assumption-of-equal-variance" class="nav-link" data-scroll-target="#assumption-of-equal-variance"> <span class="header-section-number">2.3.1</span> Assumption of equal variance</a></li>
  <li><a href="#population-distribution-and-small-sample-sizes" id="toc-population-distribution-and-small-sample-sizes" class="nav-link" data-scroll-target="#population-distribution-and-small-sample-sizes"> <span class="header-section-number">2.3.2</span> Population distribution and small sample sizes</a></li>
  <li><a href="#tests-of-paired-samples-paired-t-test" id="toc-tests-of-paired-samples-paired-t-test" class="nav-link" data-scroll-target="#tests-of-paired-samples-paired-t-test"> <span class="header-section-number">2.3.3</span> Tests of paired samples (paired t-test)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"> <span class="header-section-number">3</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Comparing means: z and t tests</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p><em>Last modified on 2022-09-12</em></p>
<div class="cell">

</div>
<div class="cell">

</div>
<section id="tests-of-significance-single-sample-inference" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Tests of Significance (single sample inference)</h1>
<p>Suppose that we want to hypothesize that the mean number of TV hours watched per week is 28.5; we’ll define this as our null hypothesis, <span class="math inline">\(H_o\)</span>. Let’s also assume that we only have access to a subset of household data (i.e.&nbsp;a sample), <span class="math inline">\(x\)</span>,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">25.7</span>, <span class="fl">38.5</span>, <span class="fl">29.3</span>, <span class="fl">25.1</span>, <span class="fl">30.6</span>, <span class="fl">34.6</span>, <span class="fl">30.0</span>, <span class="fl">39.0</span>, <span class="fl">33.7</span>, <span class="fl">31.6</span>, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>       <span class="fl">25.9</span>, <span class="fl">34.4</span>, <span class="fl">26.9</span>, <span class="fl">23.0</span>, <span class="fl">31.1</span>, <span class="fl">29.3</span>, <span class="fl">34.5</span>, <span class="fl">35.1</span>, <span class="fl">31.2</span>, <span class="fl">33.2</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>       <span class="fl">30.2</span>, <span class="fl">36.4</span>, <span class="fl">37.5</span>, <span class="fl">27.6</span>, <span class="fl">24.6</span>, <span class="fl">23.9</span>, <span class="fl">27.0</span>, <span class="fl">29.5</span>, <span class="fl">30.1</span>, <span class="fl">29.6</span>, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>       <span class="fl">27.3</span>, <span class="fl">31.2</span>, <span class="fl">32.5</span>, <span class="fl">25.7</span>, <span class="fl">30.1</span>, <span class="fl">24.2</span>, <span class="fl">24.1</span>, <span class="fl">26.4</span>, <span class="fl">31.0</span>, <span class="fl">20.7</span>, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>       <span class="fl">33.5</span>, <span class="fl">32.2</span>, <span class="fl">34.7</span>, <span class="fl">32.6</span>, <span class="fl">33.5</span>, <span class="fl">32.7</span>, <span class="fl">25.6</span>, <span class="fl">31.1</span>, <span class="fl">32.9</span>, <span class="fl">25.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>from which we can estimate the population mean and the standard error of the sample mean as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mean.x <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>SE.x   <span class="ot">&lt;-</span> <span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The arithmetic mean of <span class="math inline">\(x\)</span> is 30.14 which is slightly different from our hypothesized value of 28.5. This begs the question: is this difference significant, or is it due to chance variation alone? This question will be addressed in the following subsections.</p>
<section id="the-null-and-the-alternative-hypotheses" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="the-null-and-the-alternative-hypotheses"><span class="header-section-number">1.1</span> The null and the alternative hypotheses</h2>
<p>The objective of hypothesis testing is to assess whether the observed data are consistent with a well specified (hypothesized) random process, <span class="math inline">\(H_o\)</span>. Note that when we mean <em>random</em> here we are not inferring complete randomness but some random variation about a central value. <em>Freedman et al.</em> (2007) define The <em>null</em> and <em>alternative</em> hypotheses as follows:</p>
<blockquote class="blockquote">
<p>The <strong><em>null hypothesis</em></strong> corresponds to the idea that an observed difference is due to chance… The <strong>alternative hypothesis</strong> corresponds to the idea that the observed difference is real.</p>
</blockquote>
<p><span class="math inline">\(Ho\)</span> is a statement about the true nature of things. To assess whether our observed data are consistent with our null hypothesis we seek to compare our data with the hypothesized value .</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-2-1.png" width="480"></p>
</div>
</div>
<p>In essence, we compare our observed data (usually as a statistical summary) to the hypothesized distribution using a <em>test statistic</em> from which a <em>test of significance</em> is calculated (this tells us how likely our observed statistic agrees with our hypothesized process). These, and derived concepts, are highlighted in the subsequent sections.</p>
</section>
<section id="test-statistics" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="test-statistics"><span class="header-section-number">1.2</span> Test statistics</h2>
<p>A <strong>test statistic</strong> is a numerical summary of the data that is compared to what would be expected under the null hypothesis. Test statistics can take on many forms such as the <strong>z-tests</strong> (usually used for large datasets) or <strong>t-tests</strong> (usually used when datasets are small).</p>
</section>
<section id="z-tests" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="z-tests"><span class="header-section-number">1.3</span> <span class="math inline">\(z\)</span>-tests</h2>
<p>The <strong><span class="math inline">\(z\)</span>-statistic</strong> is a measure of how much an observed statistic differs from an expected statistic put forward by the null hypothesis. It is computed as</p>
<p><span class="math display">\[
z = \frac{observed - expected}{SE}
\]</span></p>
<p>In computing the <span class="math inline">\(z\)</span>-statistic, the <span class="math inline">\(SE\)</span> used is <em>not</em> the standard error of the observed data, but the standard error for the null. To be more precise, the <span class="math inline">\(SE\)</span> in this formula is computed from the null’s <span class="math inline">\(SD\)</span>, if given. However, in many cases (such as in this working example) the null’s <span class="math inline">\(SD\)</span> can only be estimated from the observed data’s <span class="math inline">\(SD\)</span>.</p>
<p>For example, the <span class="math inline">\(z\)</span>-statistic for our scenario is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Ho     <span class="ot">&lt;-</span> <span class="fl">28.5</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>z      <span class="ot">&lt;-</span> (mean.x <span class="sc">-</span> Ho) <span class="sc">/</span> SE.x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>where <code>SE.x</code> is the observed sample’s standard error. In our working example, <span class="math inline">\(z\)</span>’s value of <strong>2.74</strong> indicates that the sample mean is <strong>2.74</strong> <span class="math inline">\(SE\)</span> ’s away from the hypothesized value.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-4-1.png" width="672"></p>
</div>
</div>
<p>The red line shows where our observed statistic (mean number of TV hours watched) lies on the hypothesized distribution of mean values defined by <span class="math inline">\(H_o\)</span>. The grey dashed lines represent 1 <span class="math inline">\(SE\)</span> to the left and to the right of the hypothesized mean. Each tic mark interval represents a standard deviation. From the graph, it appears that the observed mean value of 30.14 is almost 3 <span class="math inline">\(SE\)</span>’s away from the hypothesized mean of 28.5. If we were to draw many samples from the population described by <span class="math inline">\(H_o\)</span> (i.e.&nbsp;a population whose mean number of TV hours watched equals 28.5), only a small fraction of the sample means would produce a <span class="math inline">\(z\)</span>-value more extreme than the one calculated from our dataset. The area shaded in light red highlights the probability of <span class="math inline">\(z\)</span>-values being more extreme than the one computed from our sample. We can quantify this probability <span class="math inline">\(P\)</span> by looking up its value in a <em>Normal distribution</em> table (the old fashion way), or more simply, by passing the <span class="math inline">\(z\)</span> parameter 2.74 to the <code>R</code> function <code>pnorm</code>.</p>
<p>The <code>pnorm</code> function gives us the probability of a <span class="math inline">\(z\)</span> value “greater than” or “less than” the <span class="math inline">\(z\)</span> value computed from our data. In this case, we are interested in knowing the probability of having <span class="math inline">\(z\)</span> values more extreme than the one computed. Since our <span class="math inline">\(z\)</span> value is on the right side of the distribution curve, we will invoke the option <code>lower.tail=FALSE</code> to ensure that the probability returned is for the right tail-end section of the distribution (the pink area in the preceding figure).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>P.Ho  <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>P.Ho</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003071959</code></pre>
</div>
</div>
<p>Here, <span class="math inline">\(z\)</span> is on the right side of the curve and the probability of getting a test statistic more extreme than our <span class="math inline">\(z\)</span> is about <strong>0.003</strong> or 0.31% . <span class="math inline">\(P\)</span> is called the <strong>observed significance level</strong> and is sometimes referred to as the <span class="math inline">\(P\)</span>-value. The <em>smaller</em> this probability, the <em>stronger</em> the evidence against <span class="math inline">\(Ho\)</span> meaning that the odds of the mean TV hours watched per household being 28.5 is very small. Careful, <span class="math inline">\(P\)</span> <strong>is not</strong> the chance of <span class="math inline">\(Ho\)</span> being right, such statement is prevalent but is <em>wrong</em>.</p>
<p>Sometimes researchers will define a <span class="math inline">\(P\)</span> value for which <span class="math inline">\(Ho\)</span> will be rejected. Such value is usually referred to as the <span class="math inline">\(\pmb{\alpha \; value}\)</span>. If such a test is requested, we must determine if the test is <strong>one-tailed</strong> or <strong>two-tailed</strong>. A test is <em>one-tailed</em> if the alternate hypothesis, <span class="math inline">\(H_a\)</span>, is of the form “greater than” or “less than” (e.g.&nbsp;the mean number of TV hours watched <em>are greater than</em> 28.5). A test is <em>two-tailed</em> if <span class="math inline">\(H_a\)</span> is <em>not</em> of the form “greater than” or “less than” (e.g.&nbsp;the mean number of TV hours watched differs from 28.5). Here are a few examples:</p>
<ul>
<li>If we chose an <span class="math inline">\(\alpha\)</span> value of 0.05 and we wanted to test the hypothesis that our observed mean hours is <strong>different</strong> than <span class="math inline">\(H_o\)</span> we would define a <strong>two-tailed</strong> test, meaning that we would have to define rejection regions associated with <span class="math inline">\(P\)</span> values of <em>less than</em> 0.025 and <em>greater than</em> 0.975 (or <span class="math inline">\(z\)</span> values of -1.96 and 1.96 respectively). The reason we choose <span class="math inline">\(p\)</span> values of 0.025/0.975 and not 0.05/0.95 is because we need to split the 0.05 <span class="math inline">\(\alpha\)</span> value across <em>both</em> tails of the curve (remember that we are rejecting the null if our <span class="math inline">\(z\)</span> value falls in <em>either</em> tails of the curve).</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-6-1.png" width="672"></p>
</div>
</div>
<ul>
<li>If we chose an <span class="math inline">\(\alpha\)</span> value of 0.05 and we wanted to test the hypothesis that our observed mean hours is <strong>greater</strong> than <span class="math inline">\(H_o\)</span>, we would define a <strong>one-tailed</strong> test, meaning that we would have to define a rejection region associated with a <span class="math inline">\(P\)</span> value <em>greater than</em> 0.95.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-7-1.png" width="672"></p>
</div>
</div>
<p>In our working example, if we had chosen a two-tailed test, we would <strong>reject</strong> the null at a 5% and 1% <span class="math inline">\(\alpha\)</span> value (these would represent rejection regions associated with <span class="math inline">\(z\)</span> values of +/- 1.96 and +/- 2.58 respectively). However, if our <span class="math inline">\(\alpha\)</span> value was set at 0.005 (0.5%), we could not reject the null hypothesis since the <span class="math inline">\(z\)</span>-value associated with a two-tailed test for <span class="math inline">\(\alpha\)</span>=0.005 is 2.81 (greater than our observed <span class="math inline">\(z\)</span> value of 2.74).</p>
<p>The following table highlights popular <span class="math inline">\(\alpha\)</span> values and their associated <span class="math inline">\(z\)</span> values for a one-tailed and two-tailed test:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><span class="math inline">\(\small\alpha=0.1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\small\alpha=0.05\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\small\alpha=0.01\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\small\alpha=0.005\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1-tailed</td>
<td style="text-align: center;">-1.28 or 1.28</td>
<td style="text-align: center;">-1.645 or 1.645</td>
<td style="text-align: center;">-2.33 or 2.33</td>
<td style="text-align: center;">-2.58 or 2.58</td>
</tr>
<tr class="even">
<td>2-tailed</td>
<td style="text-align: center;">-1.645 &amp; 1.645</td>
<td style="text-align: center;">-1.96 &amp; 1.96</td>
<td style="text-align: center;">-2.58 &amp; 2.58</td>
<td style="text-align: center;">-2.81 &amp; 2.81</td>
</tr>
</tbody>
</table>
<p>Note that the one-tailed test requires that only <strong>one</strong> condition be met (only one of the rejection regions is of concern) whereas a two-tailed test requires that <strong>two</strong> conditions be met (both rejection regions are of concern).</p>
<p>It’s important to note that the <span class="math inline">\(z\)</span>-test makes some restrictive assumptions: * the sample size is reasonably large * the normal (Gaussian) distribution can be used to approximate the distribution of the sample statistic (e.g.&nbsp;the mean) being investigated.</p>
<p>An alternative to the <span class="math inline">\(z\)</span>-test, the <span class="math inline">\(t\)</span>-test, is discussed in the following section.</p>
</section>
<section id="t-tests" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="t-tests"><span class="header-section-number">1.4</span> <span class="math inline">\(t\)</span>-tests</h2>
<p>When working with small sample sizes (typically less than 30), the <span class="math inline">\(z\)</span>-test has to be modified. For starters, the shape of the sampling distribution (i.e.&nbsp;the distribution of means one would compute from many different samples from the same underlying population) now depends on the shape of the underlying population distribution which must therefore be approximately normal in shape. These requirements can be quite restrictive because in most cases we do not know the population’s distribution.</p>
<p>Continuing with our working example, let’s assume that instead of a sample size of 50 we now have a sample size of 10.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">37.13</span>, <span class="fl">32.02</span>, <span class="fl">26.05</span>, <span class="fl">31.76</span>, <span class="fl">31.90</span>, <span class="fl">38.62</span>, <span class="fl">21.63</span>, <span class="fl">40.75</span>, <span class="fl">31.36</span>, <span class="fl">27.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next we compute the mean and standard deviation of the sample. Note that the standard deviation can be computed in one of two ways: <span class="math inline">\(TSS/\sqrt{n}\)</span> or <span class="math inline">\(TSS/\sqrt{n-1}\)</span> where <span class="math inline">\(TSS\)</span> is the <em>total sum of squares</em>, <span class="math inline">\(\sum{(x - \bar{x})^2}\)</span>, and <span class="math inline">\(n\)</span> is the sample size. The latter formulation of <span class="math inline">\(sd\)</span> (i.e.&nbsp;the one with the <span class="math inline">\(\sqrt{n-1}\)</span> in the denominator) is recommended for small sample sizes but can be used for large sample sizes as well. <code>R</code>’s <code>sd()</code> function is computed using the <span class="math inline">\(\sqrt{(n-1)}\)</span> denominator. This is what we want to use with our small sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mean.x2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(x2)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sd.x2   <span class="ot">&lt;-</span> <span class="fu">sd</span>(x2) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we compute the standard error. Recall that the standard error tells us something about the confidence in the range of <em>mean</em> values (or some other statistic) for the underlying population based on our sample; it’s <em>not</em> a measure of spread of our sample data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>SE.x2 <span class="ot">&lt;-</span> <span class="fu">sd</span>(x2) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x2)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The next step is to find the <span class="math inline">\(P\)</span>-value. When working with large sample sizes, the normal (Gaussian) distribution curve does a good job in approximating the distribution of a sample statistic (such as the mean). It does not, however, do a good job in approximating the distribution of that same statistic when these are computed from small sample sizes.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/normal_vs_student-1.png" width="576"></p>
</div>
</div>
<p>The black line represents the distribution of the <em>mean</em> hours (from many hypothetical samples) of TV watched as approximated by the <em>normal</em> curve. The red line represents the same parameter but represented this time by a <em>student</em> distribution curve with a degree of freedom, <span class="math inline">\(df\)</span>, of 4. The <span class="math inline">\(df\)</span> is computed by subtracting 1 from the total number of data points in the sample.</p>
<p>By convention when computing a test statistic for small sample sizes (and when a student curve is used), we refer to the test statistic as the <span class="math inline">\(t\)</span> statistic (or <span class="math inline">\(t\)</span> value). For our dataset <span class="math inline">\(t\)</span> can be computed as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>t.val <span class="ot">&lt;-</span> (mean.x2 <span class="sc">-</span> Ho) <span class="sc">/</span> SE.x2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, we make a point not to name the <span class="math inline">\(t\)</span> value <code>t</code> in our code since <code>R</code> has a function with the same name, <code>t()</code> (a matrix transpose function). Had we named our variable <code>t</code>, than that variable name would have masked the internal function <code>t()</code>. This would not have been a big deal for our working example since we won’t be using the <em>transpose</em> function, but it’s good practice to use variables not already in use in <code>R</code>.</p>
<p>The next step is to compute the <span class="math inline">\(P\)</span>-value. We will compute <span class="math inline">\(P\)</span> using both the normal distribution curve (which we normally do for a large sample) and <em>Student’s</em> curve (which is recommended for a small sample).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>P.Ho.norm <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(t.val, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>P.Ho.stud <span class="ot">&lt;-</span> <span class="fu">pt</span>(t.val, <span class="at">df =</span> <span class="fu">length</span>(x2) <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <span class="math inline">\(P\)</span>-value computed from the <strong>normal curve</strong> is <strong>0.038</strong> and that computed from <strong>Student’s curve</strong> is <strong>0.055</strong>. If an <span class="math inline">\(\alpha\)</span> value of 5% was requested, the normal distribution approximation would suggest that chance variation alone could not explain the discrepancy between our hypothesized mean number of TV hours watched and that computed from our sample. Yet, if Student’s approximation of the distribution is used (as it should be with the small sample), we could not reject the null (at least not at the 5% significance level).</p>
<p>The following figure summarizes the decision tree one should follow in deciding which curve to use when calculating a <span class="math inline">\(P\)</span>-value. This figure is adapted from Freedman <em>et al.</em> (p.&nbsp;493).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-13-1.png" width="710"></p>
</div>
</div>
<p>Many textbooks only cover the <span class="math inline">\(t\)</span>-test and not the <span class="math inline">\(z\)</span>-test. In fact , you may not find a <span class="math inline">\(z\)</span>-test implementation in some statistical software. This is because the <span class="math inline">\(t\)</span>-test results will converge with the <span class="math inline">\(z\)</span>-test results as the sample size gets larger.</p>
</section>
<section id="follow-up-examples" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="follow-up-examples"><span class="header-section-number">1.5</span> Follow-up examples</h2>
<section id="problem-1" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="problem-1"><span class="header-section-number">1.5.1</span> Problem 1</h3>
<p>You conduct a survey where the respondent is to answer <em>yes</em> or <em>no</em> to a question. Of the <strong>45</strong> respondents, <strong>20</strong> answer yes. You want to know if the percentage of <em>yes’</em> is significantly different from an expected value of <strong>50%</strong>.</p>
</section>
<section id="solution-to-problem-1" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="solution-to-problem-1"><span class="header-section-number">1.5.2</span> Solution to problem 1</h3>
<p>The data can be treated as a binomial proportion where the fraction of <em>yes’</em> in our sample is <span class="math inline">\(\hat{p} = 20/45 = 0.444\)</span> and the fraction of <em>no’s</em> is <span class="math inline">\(\hat{q} = 1 - \hat{p} = 1 - 0.444 = 0.555\)</span> (the <span class="math inline">\(\hat{ }\)</span> symbol reminds us that these are estimate fractions of the true yes’ and no’s in the overall population). The hypothesis <span class="math inline">\(H_o\)</span> is that the number of <em>yes’</em> in the population equals the number of <em>no’s</em> or <span class="math inline">\(p_o = q_o = 0.5\)</span>.</p>
<p>We first need to compute <span class="math inline">\(SE_{Ho}\)</span> (The standard error for the null and <em>not</em> the observed data). In this example, the standard deviation of the null hypothesis is given to us since we are told what the proportion of yes’ and no’s should be equal to in the hypothesized population (i.e.&nbsp;we know that the hypothesized population has 22.5 yes’ and 22.5 no’s). If we could not glean a standard deviation from the null, we would therefore have to rely on the sample’s <span class="math inline">\(SD\)</span> instead. <span class="math inline">\(SE_{Ho}\)</span> can be computed as follows.</p>
<p><span class="math inline">\(SE_{Ho} = \sqrt{ \frac{\displaystyle (fraction\; of\; yes')(fraction\; of\; no's)}{\displaystyle n}}=\sqrt{\frac{\displaystyle (0.5)(0.5)}{\displaystyle 45}}=0.075\)</span>.</p>
<p>A way to interpret <span class="math inline">\(SE_{Ho}\)</span> is to say that if many surveys of 45 people were collected from a population defined by the null (i.e.&nbsp;a population where the number of <em>yes’</em> equals the number of <em>no’s</em>), 68% of the fraction of <em>yes’</em> would fall between <span class="math inline">\(q_o - 1SE_{Ho}\)</span> and <span class="math inline">\(q_o + 1SE_{Ho}\)</span> or between the interval defined by the fractions (0.425, 0.575) or (42.5%, 57.5%).</p>
<p>Next, we compute the test statistic, <span class="math inline">\(z\)</span>:</p>
<p><span class="math inline">\(z = (\hat{p} - p_o)/SE_{Ho} = (.444 - 0.5)/0.075 = -0.75\)</span>,</p>
<p>The observed fraction of <em>yes’</em> is 0.75 <span class="math inline">\(SE\)</span>’s <em>below</em> the expected count of 22.5 (or 0.5 yes’).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-14-1.png" width="480"></p>
</div>
</div>
<p>Since the sample size is relatively large, we can compute the <span class="math inline">\(P\)</span>-value using the normal curve approximation using the function <code>pnorm(0.75, lower.tail=FALSE)</code> = 0.2266274.</p>
<p>The entire <code>R</code> analysis for this example can be completed as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>n   <span class="ot">&lt;-</span> <span class="dv">45</span>                        <span class="co"># number of individuals surveyed</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>p   <span class="ot">&lt;-</span> <span class="fl">0.444</span>                     <span class="co"># The fraction of yes'</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>q   <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> p                     <span class="co"># The fraction of no's</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>ho  <span class="ot">&lt;-</span> <span class="fl">0.5</span>                       <span class="co"># The null hypothesis</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>SEo <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.5</span> <span class="sc">*</span> <span class="fl">0.5</span> <span class="sc">/</span> n)       <span class="co"># The standard error for Ho sample distribution</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>z   <span class="ot">&lt;-</span> ( p <span class="sc">-</span> ho ) <span class="sc">/</span> SEo          <span class="co"># The z-statistic</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>P.z <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z, <span class="at">lower.tail=</span><span class="cn">TRUE</span>) <span class="co"># Get the probability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that in the last line of code we set <code>lower.tail</code> to TRUE since we are interested in the portion of the curve to the <em>left</em> of our test statistic. Had <span class="math inline">\(z\)</span> turned out positive (indicating that our observed fraction of yes’ is greater than expected under the null), we would have focused on right tail of the curve (i.e.&nbsp;setting <code>lower.tail</code> to FALSE).</p>
<p>Hence, there is a 23% chance that the fraction of <em>yes’</em> one could expect to measure under <span class="math inline">\(H_o\)</span> could be more extreme than the one observed or, put differently, if 100 investigators were to conduct their own survey of 45 people from a population whose number of <em>yes’</em> equals the number of <em>no’s</em>, 23 of the survey results would have a percentage of <em>yes’</em> more extreme than ours. So our observed fraction of <em>yes’</em> is consistent with what one would expect under the null hypothesis. It would probably be safe then to state that we cannot reject the null hypothesis.</p>
</section>
<section id="problem-2" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="problem-2"><span class="header-section-number">1.5.3</span> Problem 2</h3>
<p>Aldicarb, a pesticide substance, is measured from a sampling well <strong>4</strong> times over the course of a season. The concentrations measured are <strong>6.3, 7.1, 5.8 and 6.9 ppb</strong> (parts per billion). The maximum contaminant level (MCL) has been set at <strong>7 ppb</strong>. We want to determine if the average concentrations observed are less than the MCL of 7 ppb at the <strong>99% significance</strong> level.</p>
</section>
<section id="solution-to-problem-2" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="solution-to-problem-2"><span class="header-section-number">1.5.4</span> Solution to problem 2</h3>
<p>The question asks if the true mean concentration (from the four measurements) is less than or equal to 7 ppb. We do not have the luxury of monitoring this concentration continuously so we must contend with just four observations. These four observations are random variables that can be expected to fluctuate around the true mean concentration of the well (a value we are not privy to). We are hypothesizing that the true mean concentration is less than 7 ppb. We want to compare our observed mean concentration to the <em>range</em> of mean concentrations we could expect <em>if</em> we were to sample (with four concentration measurements) from a well whose mean concentration is indeed 7 ppb. If our observed concentration is not consistent with what we would expect to measure from a well whose true concentration is 7 ppb, we can than state that the <em>true</em> mean concentration of aldicarb in the well is less than 7 ppb.</p>
<p>This problem differs from the last one in that we are interested in a different parameter: the mean (of a concentration) instead of the fraction. It also differs from the last problem in that we are now defining a cutoff probability (aka a rejection region) of 0.99. In the last exercise, we were only seeking the <em>probability</em> of finding a test statistic more extreme than expected under a null (and thus leaving the interpretation of what <em>is</em> significant up to someone else).</p>
<p>We need to compute the mean of the observed concentrations, <span class="math inline">\(\hat{\mu}\)</span>, and the standard error of the mean concentrations we would observe if the null was the true state of things, <span class="math inline">\(SE_{Ho}\)</span>. For the latter, we do not know the actual standard deviation of the null distribution (this is another difference between this example and the previous example where the standard deviation–and thus the standard error–was gleaned directly from null). We will therefore assume that <span class="math inline">\(SD\)</span> of the null is the same as <span class="math inline">\(SD\)</span> from our observed data. Note that we must therefore assume that the distribution of aldicarb sample mean concentrations follows a normal curve!</p>
<p><span class="math inline">\(\hat{\mu} = \frac{\displaystyle 6.3 + 7.1 + 5.8 + 6.9}{\displaystyle 4}=6.525\)</span></p>
<p><span class="math inline">\(SE_{Ho} = \frac{\displaystyle SD_{wells}}{\sqrt{ \displaystyle n}}=\frac{\displaystyle 0.591}{\displaystyle \sqrt{4}} = 0.295\)</span>.</p>
<p>Note that we are using the <span class="math inline">\(SD\)</span> formula for small samples (i.e.&nbsp;the one with the <span class="math inline">\(\sqrt{n-1}\)</span> denominator) which just happens to be what <code>R</code> defaults to.</p>
<p>The test statistic, <span class="math inline">\(t\)</span> is computed as follows:</p>
<p><span class="math inline">\(t = (\hat{\mu} - \mu_o)/SE_{Ho} = (6.525 - 7)/0.295 = -1.6\)</span>,</p>
<p><span class="math inline">\(t\)</span> is negative implying that our observed concentration is to the left of the hypothesized value of 7. In this example, a 99% confidence interval implies that our observed mean concentration of 6.5 ppb should be at least 3 <span class="math inline">\(SE\)</span>’s to the left of our MCL of 7 ppb.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-16-1.png" width="489"></p>
</div>
</div>
<p>This dataset is very small (only 4 observations). This implies that we will want to use the student curve as opposed to the normal curve when we calculate the the <span class="math inline">\(P\)</span>-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>x   <span class="ot">&lt;-</span>  <span class="fu">c</span>(<span class="fl">6.3</span>, <span class="fl">7.1</span>, <span class="fl">5.8</span>, <span class="fl">6.9</span>)               <span class="co"># the four observed concentrations</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>n   <span class="ot">&lt;-</span> <span class="fu">length</span>(x)                            <span class="co"># number of observations </span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>mu  <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)                              <span class="co"># the mean concentration</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>ho  <span class="ot">&lt;-</span> <span class="dv">7</span>                                    <span class="co"># The null hypothesis</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>SEo <span class="ot">&lt;-</span> <span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(n)                      <span class="co"># The standard error for Ho sample distribution</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>t   <span class="ot">&lt;-</span> ( mu <span class="sc">-</span> ho ) <span class="sc">/</span> SEo                    <span class="co"># The t-statistic</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>P.z <span class="ot">&lt;-</span> <span class="fu">pt</span>(t, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)<span class="co"># Get the probability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>P.z</code> returns a value of 0.10, or 10%. In other words, 10% of the mean concentrations from samples collected from a well whose (hypothesized) mean concentration is 7 ppb could be less than our observed concentration. This implies that our observed concentration could well be from a well whose concentration hovers around 7 ppb. If that’s the case, and we were to collect more samples from the well, we could have values greater than 7 ppb (recall that the curve centered on 7 ppb represents the probability distribution of mean concentrations centered on 7 ppb). Given our <span class="math inline">\(P\)</span> value of 0.1, we cannot reject the null and therefore cannot state that our observed concentration is less than 7 ppb at a 99% significance level.</p>
</section>
</section>
<section id="using-the-built-in-t.test-function" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="using-the-built-in-t.test-function"><span class="header-section-number">1.6</span> Using the built in <strong>t.test</strong> function</h2>
<p>The six or seven lines of code used to compute the <span class="math inline">\(t\)</span>-test can easily be replaced with <code>R</code>’s <code>t.test()</code> function. Using <em>example 2</em>, we can compute the t-test as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu=</span><span class="dv">7</span>, <span class="at">alternative=</span><span class="st">"less"</span>, <span class="at">conf.level=</span> <span class="fl">0.99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at the <code>t.test()</code> parameters. <code>mu</code> is the hypothesized mean value. <code>alternative</code> determines if the test is is two-tailed (<code>="two.sided"</code>) or one-tailed (<code>="less"</code> or <code>="greater"</code>). The <code>less</code> option gives use the probability to the left of our test statistic while the <code>greater</code> option gives us the probability to the right of our test statistic. <code>conf.level</code> determines the alpha level set for <span class="math inline">\(P\)</span>.</p>
<p>Now let’s look at the output.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  x
t = -1.6077, df = 3, p-value = 0.1031
alternative hypothesis: true mean is less than 7
99 percent confidence interval:
     -Inf 7.866558
sample estimates:
mean of x 
    6.525 </code></pre>
</div>
</div>
<p>The output variables are, for the most part, self-explanatory. The value <span class="math inline">\(t\)</span> is the same as the one computed earlier. The <span class="math inline">\(P\)</span> value here gives us the probability to the <em>left</em> of our test statistic.</p>
</section>
</section>
<section id="tests-of-significance-two-independent-samples-comparison" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Tests of Significance (two independent samples comparison)</h1>
<p>Up to now, we have focused on inferences about single samples. We will now focus on comparing <em>two</em> independent samples using test statistics. The approach is very much the same except that we are no longer comparing a sample statistic to an external standard but to another sample statistic.</p>
<section id="z-test-with-two-samples-large-sample-sizes" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="z-test-with-two-samples-large-sample-sizes"><span class="header-section-number">2.1</span> <span class="math inline">\(z\)</span> test with two samples (large sample sizes)</h2>
<p>If the sample sizes in both samples are large (usually more than 30), then a <span class="math inline">\(z\)</span> test is appropriate. The <span class="math inline">\(z\)</span> statistic is computed as follows:</p>
<p><span class="math display">\[
z = \frac{observed\; difference - expected\; difference}{SE\; for\; difference}
\]</span></p>
<p>The standard error for the difference of the two samples is:</p>
<p><span class="math display">\[
SE = \sqrt{SE_{sample\; 1}^2 + SE_{sample\; 2}^2}
\]</span></p>
<section id="example" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="example"><span class="header-section-number">2.1.1</span> Example</h3>
<p>The National Assessment of Education Progress (NAEP) administered a reading test for 17 year-olds in 1990 and 2004. The <em>average</em> score was <strong>290</strong> and <strong>285</strong> respectively; a slight decrease over the course of 14 years. The standard deviation, <span class="math inline">\(SD\)</span> was <strong>40</strong> and <strong>37</strong> respectively. The sample size for both years was <strong>1000</strong>. So this begs the question, was the drop in reading assessment just a chance variation or real?<br>
<em>[This example is taken from Freedman et al., page 503]</em></p>
</section>
<section id="solution" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="solution"><span class="header-section-number">2.1.2</span> Solution</h3>
<p>The standard error for each sample can be computed as follows:</p>
<p><span class="math display">\[
SE_{1990} = \frac{SD_{1990}}{\sqrt{sample\; size}}=\frac{40}{\sqrt{1000}} = 1.26
\]</span></p>
<p><span class="math display">\[
SE_{2004} = \frac{SD_{2000}}{\sqrt{sample\; size}}=\frac{37}{\sqrt{1000}} = 1.17
\]</span></p>
<p>The standard error for the difference can be computed as follows:</p>
<p><span class="math display">\[
SE = \sqrt{SE_{1990}^2 + SE_{2004}^2} = \sqrt{1.26^2 + 1.17^2} = 1.72
\]</span></p>
<p>Finally, we can compute <span class="math inline">\(z\)</span> as follows (keeping in mind that the <em>expected</em> difference between both years is our null hypothesis, i.e.&nbsp;no difference, 0):</p>
<p><span class="math display">\[
z = \frac{(score_{2004} - score_{1990}) - (expected\; difference)}{SE\; of\; difference}=\frac{(285-290) - 0}{1.72} = -2.9
\]</span></p>
<p>So the difference is <strong>2.9</strong> <span class="math inline">\(SE\)</span>’s below what would be expected if <span class="math inline">\(Ho\)</span> (i.e.&nbsp;no difference between years) was true. Looking up the <span class="math inline">\(P\)</span> value for an <span class="math inline">\(SE\)</span> of 2.9 on a normal curve is <strong>0.002</strong>. Put differently, if their was truly no difference in reading scores between both years, then the odds of getting a <span class="math inline">\(z\)</span> score as extreme as the one we just computed is 0.1%. If we had defined an <span class="math inline">\(\alpha\)</span> confidence value of 5% or even 1%, we could conclude that the difference between both years is real.</p>
<p>The following figure illustrates the result.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-20-1.png" width="576"></p>
</div>
</div>
<p>The black curve encompasses the difference in scores between years one would <em>expect</em> to observe from many samples drawn under the assumption that the <em>difference in scores between both years is only due to chance variability alone</em>. The red vertical line shows where our value lies; far into the left-end tail.</p>
<p>The above can be coded in <code>R</code> as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>SE<span class="fl">.1990</span> <span class="ot">&lt;-</span>  <span class="dv">40</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">1000</span>)               </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>SE<span class="fl">.2004</span> <span class="ot">&lt;-</span>  <span class="dv">37</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">1000</span>)  </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>SE      <span class="ot">&lt;-</span> <span class="fu">sqrt</span>( SE<span class="fl">.1990</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> SE<span class="fl">.2004</span><span class="sc">^</span><span class="dv">2</span>)                        </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>z       <span class="ot">&lt;-</span> (<span class="dv">285</span> <span class="sc">-</span> <span class="dv">290</span>) <span class="sc">/</span> SE</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>P.z     <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The variable <code>z</code> stores the test statistic and the variable <code>P.z</code> stores the probability <span class="math inline">\(P\)</span>.</p>
</section>
</section>
<section id="t-test-with-two-samples-small-sample-sizes" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="t-test-with-two-samples-small-sample-sizes"><span class="header-section-number">2.2</span> <span class="math inline">\(t\)</span> test with two samples (small sample sizes )</h2>
<p>If the sample sizes in at least one of the two samples is small (usually less than 30), then a <span class="math inline">\(t\)</span> test is appropriate. Note that a <span class="math inline">\(t\)</span> test can also be used with large samples as well, in some cases, statistical packages will only compute a <span class="math inline">\(t\)</span> test and not a <span class="math inline">\(z\)</span> test.</p>
<p>To use the <span class="math inline">\(t\)</span>-statistic, the two samples must be:</p>
<ul>
<li>from normally distributed populations,</li>
<li>from populations with equal variances,</li>
<li>uncensored.</li>
</ul>
<p>Many times, the aforementioned criteria are not known and may have to be assumed if theory allows.</p>
<p>If the assumption of equal variances is met, the standard error can be pooled from both sample’s standard errors.</p>
<p><span class="math display">\[
SE_{pooled} = \sqrt{\frac{(n_1 - 1)SD_1^2+(n_2 - 1)SD_2^2}{n_1 + n_2 - 2}}
\]</span></p>
<p>Subscripts <span class="math inline">\(1\)</span> and <span class="math inline">\(2\)</span> denote samples 1 and 2. Note that we are using <span class="math inline">\(SD_1\)</span> and <span class="math inline">\(SD_2\)</span> in this equation as opposed to <span class="math inline">\(SE_1\)</span> and <span class="math inline">\(SE_2\)</span>. The test statistic <span class="math inline">\(t\)</span> is therefore computed as follows:</p>
<p><span class="math display">\[
t = \frac{(observed\; difference - expected\; difference) - hypothesized\; difference}
         {SE_{pooled}\sqrt{1/n_1 + 1/n_2}}
\]</span></p>
<p>The <span class="math inline">\(t\)</span> value is then used to look up the <span class="math inline">\(P\)</span> value on a Student curve using <span class="math inline">\(n_1 + n_2 - 2\)</span> degrees of freedom.</p>
<section id="example-1" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="example-1"><span class="header-section-number">2.2.1</span> Example</h3>
<p>Groundwater sulfate concentrations are monitored at a contaminated site over the course of a year. Those concentrations are compared to ones measured at background sites for the same time period. You want to determine if the concentration at the contaminated site is significantly larger than that for the background site. The concentrations of sulfate (in ppm) for both sites are as follows:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Contaminated</th>
<th style="text-align: left;">Background</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">600</td>
<td style="text-align: left;">560</td>
</tr>
<tr class="even">
<td style="text-align: left;">590</td>
<td style="text-align: left;">550</td>
</tr>
<tr class="odd">
<td style="text-align: left;">570</td>
<td style="text-align: left;">570</td>
</tr>
<tr class="even">
<td style="text-align: left;">570</td>
<td style="text-align: left;">550</td>
</tr>
<tr class="odd">
<td style="text-align: left;">565</td>
<td style="text-align: left;">570</td>
</tr>
<tr class="even">
<td style="text-align: left;">580</td>
<td style="text-align: left;">590</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">550</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">580</td>
</tr>
</tbody>
</table>
</section>
<section id="solution-1" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="solution-1"><span class="header-section-number">2.2.2</span> Solution</h3>
<p>You will setup this problem as follows: the null hypothesis, <span class="math inline">\(H_o\)</span>, states that the concentrations between both sites is the same; the alternative hypothesis, <span class="math inline">\(H_a\)</span>, states that the contaminated site has a concentration greater than the background.</p>
<p>We will reference the contaminated site with the <span class="math inline">\(1\)</span> subscript and the background site with the subscript <span class="math inline">\(2\)</span>. The means and standard deviations are <span class="math inline">\(\mu_1 = 579.2\)</span>, <span class="math inline">\(\mu_2 = 565\)</span>, <span class="math inline">\(SD_1 = 13.6\)</span> and <span class="math inline">\(SD_2 = 15.1\)</span>.</p>
<p>The pooled standard error of the mean is therefore:</p>
<p><span class="math display">\[
SE_{pooled} = \sqrt{\frac{(6 - 1)13.6^2+(8 - 1)15.1^2}{6 + 8 - 2}}=14.5
\]</span></p>
<p>and <span class="math inline">\(t\)</span> is:</p>
<p><span class="math display">\[
t = \frac{(579.2-565) - 0)}{14.5\sqrt{1/6 + 1/8}} = 1.8
\]</span></p>
<p>One <span class="math inline">\(SE\)</span> is <span class="math inline">\(14.5\sqrt{1/6 + 1/8}=\)</span> <strong>7.8</strong> ppm, therefore our observed difference of <strong>14.2</strong> ppm (computed from 579.2 - 565) is <strong>1.8</strong> <span class="math inline">\(SE\)</span> from the expected difference of 0 (recall that for a <span class="math inline">\(t\)</span>-test <span class="math inline">\(SE\)</span> equals <span class="math inline">\(SE_{pooled}\sqrt{1/n_1 + 1/n_2}\)</span>). Looking up the <span class="math inline">\(P\)</span> value on a Student curve gives us a probability of <strong>0.048</strong> (i.e.&nbsp;there is a 4.8% chance that, assuming there is no difference in concentrations between sites, the difference between means would be greater than that observed by chance variation alone).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="z_t_tests_files/figure-html/unnamed-chunk-22-1.png" width="672"></p>
</div>
</div>
<p>The following block of code runs the entire analysis. Here, the data are entered manually. If data are loaded from a file into a data frame, you can set the variables <code>s1</code> and <code>s2</code> equal to the pertinent columns in the data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">600</span>, <span class="dv">590</span>, <span class="dv">570</span>, <span class="dv">570</span>, <span class="dv">565</span>, <span class="dv">580</span>)             <span class="co"># Contaminated site</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">560</span>, <span class="dv">550</span>, <span class="dv">570</span>, <span class="dv">550</span>, <span class="dv">570</span>, <span class="dv">590</span>, <span class="dv">550</span>, <span class="dv">580</span>)   <span class="co"># Background sites</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>SD1 <span class="ot">&lt;-</span> <span class="fu">sd</span>(s1)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>SD2 <span class="ot">&lt;-</span> <span class="fu">sd</span>(s2)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>SE  <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(((<span class="fu">length</span>(s1) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> SD1<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="fu">length</span>(s2) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> SD2<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="fu">length</span>(s1) <span class="sc">+</span> <span class="fu">length</span>(s2) <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>t   <span class="ot">&lt;-</span> ((<span class="fu">mean</span>(s1) <span class="sc">-</span> <span class="fu">mean</span>(s2)) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> (SE <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">length</span>(s1) <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">length</span>(s2)))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>P   <span class="ot">&lt;-</span> <span class="fu">pt</span>(t, <span class="at">df =</span> <span class="fu">length</span>(s1) <span class="sc">+</span> <span class="fu">length</span>(s2) <span class="sc">-</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The variable <code>P</code> stores the probability value 0.0477 and variable <code>t</code> stores the value 1.81.</p>
<p>You can use the <code>t.test</code> function <em>if</em> the data are used to compute the <span class="math inline">\(t\)</span> test. If you only have the means, standard deviations and sample sizes at your disposal (and not the raw data), you must compute <span class="math inline">\(t\)</span> and <span class="math inline">\(P\)</span> as shown in the last code block. Since we have the original concentrations for both the contaminated and background sites in this example, we can run the <code>t.test</code> as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(s1, s2, <span class="at">var.equal=</span><span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This returns the following values:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  s1 and s2
t = 1.8099, df = 12, p-value = 0.04771
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 0.2157541       Inf
sample estimates:
mean of x mean of y 
 579.1667  565.0000 </code></pre>
</div>
</div>
<p>Note that the <code>t.test</code> function can also be used to run a <span class="math inline">\(z\)</span>-test between means if tabulated data are available.</p>
</section>
</section>
<section id="notes-on-z-and-t-tests" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="notes-on-z-and-t-tests"><span class="header-section-number">2.3</span> Notes on z and t tests</h2>
<section id="assumption-of-equal-variance" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="assumption-of-equal-variance"><span class="header-section-number">2.3.1</span> Assumption of equal variance</h3>
<p>One assumption that needs to be met when conducting a test of significance with small sample sizes is the equality of variances between samples. This is an assumption we have made thus far in our working examples. But such an assumption may not be tenable in real life. If such is the case, you may want to resort to alternate techniques such as robust test of significance techniques. However, if you are working with the raw data, you can use the <code>t.test</code> function along with the parameter <code>var.equal=FALSE</code> option set. This option invokes <a href="http://en.wikipedia.org/wiki/Welch's_t_test">Welch’s</a> variance approximation which is believed to provide a more robust <span class="math inline">\(t\)</span>-test analysis. Working with the last example, we can compute the <span class="math inline">\(t\)</span>-test using Welch’s approximation as demonstrated in the following line of code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(s1, s2, <span class="at">var.equal=</span><span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note the <code>var.equal=FALSE</code> option (this is the default option if not explicitly defined). The output of this function is shown below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  s1 and s2
t = 1.8402, df = 11.514, p-value = 0.04582
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 0.3974713       Inf
sample estimates:
mean of x mean of y 
 579.1667  565.0000 </code></pre>
</div>
</div>
<p>Interestingly, the Welch’s <span class="math inline">\(t\)</span>-test returns a smaller <span class="math inline">\(P\)</span> value. It must be noted that Welch’s <span class="math inline">\(t\)</span>-test also has its limitations. If in doubt, you might want to revert to more <strong>robust</strong> tests of significance such as the Wilcoxon rank-sum tests or permutation tests.</p>
<p>Note that equality of variances between two samples can be tested using the <strong><span class="math inline">\(F\)</span> test</strong>.</p>
</section>
<section id="population-distribution-and-small-sample-sizes" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="population-distribution-and-small-sample-sizes"><span class="header-section-number">2.3.2</span> Population distribution and small sample sizes</h3>
<p>If the sample size is small, the shape of the population distribution will influence the tests. If the population is not normally distributed, the data may need to be transformed prior to conducting a <span class="math inline">\(t\)</span>-test. Many environmental data such as <em>concentrations of “something”</em> tend to be positively skewed. If such is the case, a popular transformation for skewed data is the natural logarithm transformation, <code>log</code>. Note that when you are conducting a <span class="math inline">\(t\)</span> or <span class="math inline">\(z\)</span> test on log transformed data, you are conducting a hypothesis test on the <strong>ratio of the medians</strong> and <em>not</em> a hypothesis about the difference of the means (Millard <em>et al.</em>, p.&nbsp;416-417).</p>
<p>For example, using TcCB concentration data between a background, <code>Ref</code>, and contaminated site, <code>Cont</code> (Millard et al., p.420),</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>Ref <span class="ot">&lt;-</span>  <span class="fu">c</span>(<span class="fl">0.22</span>,<span class="fl">0.23</span>,<span class="fl">0.26</span>,<span class="fl">0.27</span>,<span class="fl">0.28</span>,<span class="fl">0.28</span>,<span class="fl">0.29</span>,<span class="fl">0.33</span>,<span class="fl">0.34</span>,<span class="fl">0.35</span>,<span class="fl">0.38</span>,<span class="fl">0.39</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.39</span>,<span class="fl">0.42</span>,<span class="fl">0.42</span>,<span class="fl">0.43</span>,<span class="fl">0.45</span>,<span class="fl">0.46</span>,<span class="fl">0.48</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>,<span class="fl">0.51</span>,<span class="fl">0.52</span>,<span class="fl">0.54</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.56</span>,<span class="fl">0.56</span>,<span class="fl">0.57</span>,<span class="fl">0.57</span>,<span class="fl">0.6</span>,<span class="fl">0.62</span>,<span class="fl">0.63</span>,<span class="fl">0.67</span>,<span class="fl">0.69</span>,<span class="fl">0.72</span>,<span class="fl">0.74</span>,<span class="fl">0.76</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.79</span>,<span class="fl">0.81</span>,<span class="fl">0.82</span>,<span class="fl">0.84</span>,<span class="fl">0.89</span>,<span class="fl">1.11</span>,<span class="fl">1.13</span>,<span class="fl">1.14</span>,<span class="fl">1.14</span>,<span class="fl">1.2</span>,<span class="fl">1.33</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>Cont <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.09</span>,<span class="fl">0.09</span>,<span class="fl">0.09</span>,<span class="fl">0.12</span>,<span class="fl">0.12</span>,<span class="fl">0.14</span>,<span class="fl">0.16</span>,<span class="fl">0.17</span>,<span class="fl">0.17</span>,<span class="fl">0.17</span>,<span class="fl">0.18</span>,<span class="fl">0.19</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.2</span>,<span class="fl">0.2</span>,<span class="fl">0.21</span>,<span class="fl">0.21</span>,<span class="fl">0.22</span>,<span class="fl">0.22</span>,<span class="fl">0.22</span>,<span class="fl">0.23</span>,<span class="fl">0.24</span>,<span class="fl">0.25</span>,<span class="fl">0.25</span>,<span class="fl">0.25</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.25</span>,<span class="fl">0.26</span>,<span class="fl">0.28</span>,<span class="fl">0.28</span>,<span class="fl">0.29</span>,<span class="fl">0.31</span>,<span class="fl">0.33</span>,<span class="fl">0.33</span>,<span class="fl">0.33</span>,<span class="fl">0.34</span>,<span class="fl">0.37</span>,<span class="fl">0.38</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.39</span>,<span class="fl">0.4</span>,<span class="fl">0.43</span>,<span class="fl">0.43</span>,<span class="fl">0.47</span>,<span class="fl">0.48</span>,<span class="fl">0.48</span>,<span class="fl">0.49</span>,<span class="fl">0.51</span>,<span class="fl">0.51</span>,<span class="fl">0.54</span>,<span class="fl">0.6</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.61</span>,<span class="fl">0.62</span>,<span class="fl">0.75</span>,<span class="fl">0.82</span>,<span class="fl">0.85</span>,<span class="fl">0.92</span>,<span class="fl">0.94</span>,<span class="fl">1.05</span>,<span class="fl">1.1</span>,<span class="fl">1.1</span>,<span class="fl">1.19</span>,<span class="fl">1.22</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>        <span class="fl">1.33</span>,<span class="fl">1.39</span>,<span class="fl">1.39</span>,<span class="fl">1.52</span>,<span class="fl">1.53</span>,<span class="fl">1.73</span>,<span class="fl">2.35</span>,<span class="fl">2.46</span>,<span class="fl">2.59</span>,<span class="fl">2.61</span>,<span class="fl">3.06</span>,<span class="fl">3.29</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>        <span class="fl">5.56</span>,<span class="fl">6.61</span>,<span class="fl">18.4</span>,<span class="fl">51.97</span>,<span class="fl">168.64</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>we can test the null hypothesis that the concentrations between both wells are equal using the raw (un-transformed) data (to be conservative, we will assume that the variances are not equal and invoke Welch’s assumption about the variance),</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Cont,Ref,<span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">var.equal=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which gives us the following:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Cont and Ref
t = 1.4538, df = 76.05, p-value = 0.07506
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 -0.4821023        Inf
sample estimates:
mean of x mean of y 
3.9151948 0.5985106 </code></pre>
</div>
</div>
<p>The test statitic of <strong>1.45</strong> indicates that there is a <strong>7.5%</strong> chance that we could see a test statistic more extreme under <span class="math inline">\(H_o\)</span> than the one computed.</p>
<p>If we log-transform the data, we get</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="fu">log</span>(Cont),<span class="fu">log</span>(Ref),<span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">var.equal=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which gives us the following:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  log(Cont) and log(Ref)
t = 0.42589, df = 101.99, p-value = 0.3355
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 -0.2090447        Inf
sample estimates:
 mean of x  mean of y 
-0.5474262 -0.6195712 </code></pre>
</div>
</div>
<p>Notice the larger <span class="math inline">\(P\)</span> value of <em>%33.5</em> which indicates that we should not reject the null and that for all intents and purposes, we cannot dismiss the chance that the differences in <em>median</em> concentrations (as expressed by a ratio) are due to variability alone. Remember that by log-transforming the data we are looking at the ratio of the <em>medians</em>, not the difference between means, so interpret these results with caution!</p>
<p>Other methods used to test the normality of the data are tests of <strong>skewness</strong> and <strong>kurtosis</strong>.</p>
</section>
<section id="tests-of-paired-samples-paired-t-test" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="tests-of-paired-samples-paired-t-test"><span class="header-section-number">2.3.3</span> Tests of paired samples (paired t-test)</h3>
<p>Suppose that you want to compare concentrations of ozone between two locations on a <em>set of dates</em> (i.e.&nbsp;for each date, ozone concentrations are compared between two sites). This problem differs from the groundwater sulfate example shown earlier in that a sample from each location is paired. This violates one of the <span class="math inline">\(z\)</span> and <span class="math inline">\(t\)</span> test requirements in that samples from <em>both</em> groups be independent of each other. In the case of the ozone concentration, this assumption does not hold. However, Freedman <em>et al.</em> (page 510) explain that the errors introduced (in estimating <span class="math inline">\(SE\)</span>) when violating this assumption tend to cancel each other out when applied to paired tests. Using data from Millard <em>et al.</em> (page 408) where ozone concentrations for two areas (Yonkers, NY and Stamford, CT) are collected on a daily bases the <strong>paired <span class="math inline">\(t\)</span>-test</strong> can be computed by invoking the <code>paired = TRUE</code> option.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ozone concentrations in ppb)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>yonkers <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">47</span>,<span class="dv">37</span>,<span class="dv">45</span>,<span class="dv">52</span>,<span class="dv">51</span>,<span class="dv">22</span>,<span class="dv">27</span>,<span class="dv">25</span>,<span class="dv">55</span>,<span class="dv">72</span>,<span class="dv">132</span>,<span class="dv">106</span>,<span class="dv">42</span>,<span class="dv">45</span>,<span class="dv">80</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>            <span class="dv">107</span>,<span class="dv">21</span>,<span class="dv">50</span>,<span class="dv">31</span>,<span class="dv">37</span>,<span class="dv">19</span>,<span class="dv">33</span>,<span class="dv">22</span>,<span class="dv">45</span>,<span class="dv">36</span>,<span class="dv">24</span>,<span class="dv">88</span>,<span class="dv">111</span>,<span class="dv">117</span>,<span class="dv">31</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>            <span class="dv">37</span>,<span class="dv">93</span>,<span class="dv">106</span>,<span class="dv">64</span>,<span class="dv">83</span>,<span class="dv">97</span>,<span class="dv">79</span>,<span class="dv">36</span>,<span class="dv">51</span>,<span class="dv">75</span>,<span class="dv">104</span>,<span class="dv">107</span>,<span class="dv">68</span>,<span class="dv">19</span>,<span class="dv">67</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>            <span class="dv">20</span>,<span class="dv">35</span>,<span class="dv">30</span>,<span class="dv">31</span>,<span class="dv">81</span>,<span class="dv">119</span>,<span class="dv">76</span>,<span class="dv">108</span>,<span class="dv">85</span>,<span class="dv">96</span>,<span class="dv">48</span>,<span class="dv">60</span>,<span class="dv">54</span>,<span class="dv">71</span>,<span class="dv">50</span>,<span class="dv">37</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>            <span class="dv">47</span>,<span class="dv">71</span>,<span class="dv">46</span>,<span class="dv">41</span>,<span class="dv">49</span>,<span class="dv">59</span>,<span class="dv">25</span>,<span class="dv">45</span>,<span class="dv">40</span>,<span class="dv">13</span>,<span class="dv">46</span>,<span class="dv">62</span>,<span class="dv">80</span>,<span class="dv">39</span>,<span class="dv">74</span>,<span class="dv">66</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>            <span class="dv">82</span>,<span class="dv">47</span>,<span class="dv">28</span>,<span class="dv">44</span>,<span class="dv">55</span>,<span class="dv">34</span>,<span class="dv">60</span>,<span class="dv">70</span>,<span class="dv">41</span>,<span class="dv">96</span>,<span class="dv">54</span>,<span class="dv">100</span>,<span class="dv">44</span>,<span class="dv">44</span>,<span class="dv">75</span>,<span class="dv">86</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>            <span class="dv">70</span>,<span class="dv">53</span>,<span class="dv">36</span>,<span class="dv">117</span>,<span class="dv">43</span>,<span class="dv">27</span>,<span class="dv">77</span>,<span class="dv">75</span>,<span class="dv">87</span>,<span class="dv">47</span>,<span class="dv">114</span>,<span class="dv">66</span>,<span class="dv">18</span>,<span class="dv">25</span>,<span class="dv">14</span>,<span class="dv">27</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>            <span class="dv">9</span>,<span class="dv">16</span>,<span class="dv">67</span>,<span class="dv">74</span>,<span class="dv">74</span>,<span class="dv">75</span>,<span class="dv">74</span>,<span class="dv">42</span>,<span class="dv">38</span>,<span class="dv">23</span>,<span class="dv">50</span>,<span class="dv">34</span>,<span class="dv">58</span>,<span class="dv">35</span>,<span class="dv">24</span>,<span class="dv">27</span>,<span class="dv">17</span>,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>            <span class="dv">21</span>,<span class="dv">14</span>,<span class="dv">32</span>,<span class="dv">51</span>,<span class="dv">15</span>,<span class="dv">21</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>stamford <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">66</span>,<span class="dv">52</span>,<span class="dv">49</span>,<span class="dv">64</span>,<span class="dv">68</span>,<span class="dv">26</span>,<span class="dv">86</span>,<span class="dv">52</span>,<span class="dv">75</span>,<span class="dv">87</span>,<span class="dv">188</span>,<span class="dv">103</span>,<span class="dv">82</span>,<span class="dv">71</span>,<span class="dv">103</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>             <span class="dv">240</span>,<span class="dv">31</span>,<span class="dv">40</span>,<span class="dv">47</span>,<span class="dv">51</span>,<span class="dv">31</span>,<span class="dv">47</span>,<span class="dv">14</span>,<span class="dv">71</span>,<span class="dv">61</span>,<span class="dv">47</span>,<span class="dv">196</span>,<span class="dv">131</span>,<span class="dv">173</span>,<span class="dv">37</span>,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>             <span class="dv">47</span>,<span class="dv">215</span>,<span class="dv">230</span>,<span class="dv">69</span>,<span class="dv">98</span>,<span class="dv">125</span>,<span class="dv">94</span>,<span class="dv">72</span>,<span class="dv">72</span>,<span class="dv">125</span>,<span class="dv">143</span>,<span class="dv">192</span>,<span class="dv">122</span>,<span class="dv">32</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>             <span class="dv">114</span>,<span class="dv">32</span>,<span class="dv">23</span>,<span class="dv">71</span>,<span class="dv">38</span>,<span class="dv">136</span>,<span class="dv">169</span>,<span class="dv">152</span>,<span class="dv">201</span>,<span class="dv">134</span>,<span class="dv">206</span>,<span class="dv">92</span>,<span class="dv">101</span>,<span class="dv">119</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>             <span class="dv">124</span>,<span class="dv">83</span>,<span class="dv">60</span>,<span class="dv">124</span>,<span class="dv">142</span>,<span class="dv">124</span>,<span class="dv">64</span>,<span class="dv">75</span>,<span class="dv">103</span>,<span class="dv">46</span>,<span class="dv">68</span>,<span class="dv">87</span>,<span class="dv">27</span>,<span class="dv">73</span>,<span class="dv">59</span>,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>             <span class="dv">119</span>,<span class="dv">64</span>,<span class="dv">111</span>,<span class="dv">80</span>,<span class="dv">68</span>,<span class="dv">24</span>,<span class="dv">24</span>,<span class="dv">82</span>,<span class="dv">100</span>,<span class="dv">55</span>,<span class="dv">91</span>,<span class="dv">87</span>,<span class="dv">64</span>,<span class="dv">170</span>,<span class="dv">86</span>,<span class="dv">202</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>             <span class="dv">71</span>,<span class="dv">85</span>,<span class="dv">122</span>,<span class="dv">155</span>,<span class="dv">80</span>,<span class="dv">71</span>,<span class="dv">28</span>,<span class="dv">212</span>,<span class="dv">80</span>,<span class="dv">24</span>,<span class="dv">80</span>,<span class="dv">169</span>,<span class="dv">174</span>,<span class="dv">141</span>,<span class="dv">202</span>,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>             <span class="dv">113</span>,<span class="dv">38</span>,<span class="dv">38</span>,<span class="dv">28</span>,<span class="dv">52</span>,<span class="dv">14</span>,<span class="dv">38</span>,<span class="dv">94</span>,<span class="dv">89</span>,<span class="dv">99</span>,<span class="dv">150</span>,<span class="dv">146</span>,<span class="dv">113</span>,<span class="dv">66</span>,<span class="dv">38</span>,<span class="dv">80</span>,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>             <span class="dv">80</span>,<span class="dv">99</span>,<span class="dv">71</span>,<span class="dv">42</span>,<span class="dv">52</span>,<span class="dv">33</span>,<span class="dv">38</span>,<span class="dv">24</span>,<span class="dv">61</span>,<span class="dv">108</span>,<span class="dv">38</span>,<span class="dv">28</span>)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(stamford, yonkers, <span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">var.equal=</span><span class="cn">FALSE</span>, <span class="at">paired=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  stamford and yonkers
t = 13.044, df = 131, p-value &lt; 0.00000000000000022
alternative hypothesis: true mean difference is greater than 0
95 percent confidence interval:
 30.52863      Inf
sample estimates:
mean difference 
        34.9697 </code></pre>
</div>
</div>
<div class="cell">

</div>
<p>The <span class="math inline">\(t\)</span>-test result can be interpreted in the same way. The test statistic of 13.04 is way up in the right-tail end side of the curve. Its associated probability of nearly 0 indicates that the differences in ozone concentrations between both locations cannot be explained by chance variability alone. Note that even though we invoked the <span class="math inline">\(t\)</span> test the results are identical to what we would have gotten had we performed a <span class="math inline">\(z\)</span> test since the sample size is large.</p>
</section>
</section>
</section>
<section id="references" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> References</h1>
<p>Freedman D.A., Robert Pisani, Roger Purves. <em>Statistics</em>, 4th edition, 2007.<br>
Millard S.P, Neerchal N.K., <em>Environmental Statistics with S-Plus</em>, 2001.<br>
McClave J.T., Dietrich F.H., <em>Statistics</em>, 4th edition, 1988.</p>
<hr>
<p><strong>Session Info</strong>:</p>
<div class="cell-output-display">
<p><strong>R version 4.2.1 (2022-06-23 ucrt)</strong></p>
<p><strong>Platform:</strong> x86_64-w64-mingw32/x64 (64-bit)</p>
<p><strong>attached base packages:</strong> <em>stats</em>, <em>graphics</em>, <em>grDevices</em>, <em>utils</em>, <em>datasets</em>, <em>methods</em> and <em>base</em></p>
<p><strong>other attached packages:</strong> extrafont(v.0.18)</p>
<p><strong>loaded via a namespace (and not attached):</strong> <em>Rcpp(v.1.0.9)</em>, <em>digest(v.0.6.29)</em>, <em>Rttf2pt1(v.1.3.8)</em>, <em>jsonlite(v.1.8.0)</em>, <em>magrittr(v.2.0.3)</em>, <em>evaluate(v.0.16)</em>, <em>rlang(v.1.0.4)</em>, <em>stringi(v.1.7.8)</em>, <em>cli(v.3.3.0)</em>, <em>rstudioapi(v.0.14)</em>, <em>extrafontdb(v.1.0)</em>, <em>rmarkdown(v.2.16)</em>, <em>tools(v.4.2.1)</em>, <em>pander(v.0.6.5)</em>, <em>stringr(v.1.4.1)</em>, <em>xfun(v.0.32)</em>, <em>yaml(v.2.3.5)</em>, <em>fastmap(v.1.1.0)</em>, <em>compiler(v.4.2.1)</em>, <em>htmltools(v.0.5.3)</em> and <em>knitr(v.1.40)</em></p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-right">Creative Commons License, Manny Gimond, 2022</div>
  </div>
</footer>



</body></html>